import { 
  DepartmentInfo, 
  UserProfile, 
  RailwayCorridor, 
  CorridorAsset, 
  MaintenanceTask, 
  ServiceRequest, 
  ResourceItem, 
  AiRecommendation, 
  NotificationItem, 
  AuditLogEntry,
  BundledMaintenanceOrder,
  LiveTrain,
  MaintenanceBlockRequest,
  StatutoryT806Sanction
} from "./types";
import {
  BHOPAL_ITARSI_CORRIDOR,
  MOCK_CORRIDOR_ASSETS,
  MOCK_LIVE_TRAINS as BASE_TRAINS,
  MOCK_BLOCK_REQUESTS as BASE_BLOCKS,
  MOCK_T806_SANCTIONS as BASE_SANCTIONS,
  MOCK_RBAC_PERSONAS
} from "./bhopalItarsiData";
import {
  ALL_EXPANDED_CORRIDORS,
  EXPANDED_ASSETS_DATA,
  EXPANDED_TRAINS_DATA,
  EXPANDED_BLOCK_REQUESTS_DATA,
  EXPANDED_SANCTIONS_DATA
} from "./expandedCorridorsData";

export {
  BHOPAL_ITARSI_CORRIDOR,
  ALL_EXPANDED_CORRIDORS,
  MOCK_CORRIDOR_ASSETS,
  MOCK_RBAC_PERSONAS
};

export const MOCK_LIVE_TRAINS = EXPANDED_TRAINS_DATA;
export const MOCK_BLOCK_REQUESTS = EXPANDED_BLOCK_REQUESTS_DATA;
export const MOCK_T806_SANCTIONS = EXPANDED_SANCTIONS_DATA;
export const MOCK_ASSETS = EXPANDED_ASSETS_DATA;
export const MOCK_CORRIDORS = ALL_EXPANDED_CORRIDORS;

export const MOCK_USERS: UserProfile[] = [
  {
    id: "USR-ADM-01",
    name: "Rajesh Verma",
    email: "admin@railplan.ai",
    role: "CENTRAL_ADMIN",
    designation: "Executive Director (Railway Board)",
    zone: "Railway Board (Central Authority)",
    division: "Central Authority (Railway Board)",
  },
  {
    id: "USR-ENG-01",
    name: "Sunil Deshmukh",
    email: "civil@railplan.ai",
    role: "DEPT_USER",
    departmentId: "ENG",
    departmentName: "Civil",
    designation: "Senior Section Engineer (Civil / Permanent Way)",
    zone: "Northern Railway (NR)",
    division: "Delhi Division",
  },
  {
    id: "USR-ELEC-01",
    name: "K. Ramanathan",
    email: "electrical@railplan.ai",
    role: "DEPT_USER",
    departmentId: "ELEC",
    departmentName: "Electrical/OHE",
    designation: "Chief Electrical Traction & OHE Engineer",
    zone: "Western Railway (WR)",
    division: "Vadodara Division",
  },
  {
    id: "USR-SNT-01",
    name: "Ananya Sharma",
    email: "signal@railplan.ai",
    role: "DEPT_USER",
    departmentId: "SNT",
    departmentName: "Signal & Traffic",
    designation: "Chief Signal & Kavach Systems Engineer",
    zone: "Western Railway (WR)",
    division: "Mumbai Division",
  },
  {
    id: "USR-SFTY-01",
    name: "Devendra Yadav",
    email: "safety@railplan.ai",
    role: "DEPT_USER",
    departmentId: "SFTY",
    departmentName: "Safety",
    designation: "Chief Safety Officer & CRS Compliance Inspector",
    zone: "Railway Board (Central Authority)",
    division: "Safety Directorate",
  },
];

export const MOCK_DEPARTMENTS: DepartmentInfo[] = [
  {
    id: "ENG",
    name: "Civil Engineering (P-Way)",
    code: "CIVIL",
    headName: "Sunil Deshmukh",
    email: "civil@railplan.ai",
    userCount: 362,
    activeTasks: 18,
    pendingRequests: 5,
    allocatedBudget: 65000000,
    usedBudget: 40400000,
    workforceTotal: 1430,
    workforceActive: 1215,
    equipmentCount: 123,
    performanceScore: 93,
    color: "#2DC7D5", // Ice Sky Blue
    description: "Civil infrastructure, Permanent Way (P-Way), track geometry, rails, sleepers, ballast, formations, bridges, culverts, and structural safety maintenance.",
  },
  {
    id: "ELEC",
    name: "Electrical / 25kV Traction",
    code: "ELEC",
    headName: "K. Ramanathan",
    email: "electrical@railplan.ai",
    userCount: 115,
    activeTasks: 9,
    pendingRequests: 2,
    allocatedBudget: 22000000,
    usedBudget: 11800000,
    workforceTotal: 390,
    workforceActive: 340,
    equipmentCount: 42,
    performanceScore: 94,
    color: "#00FFD2", // Cyber Mint
    description: "25kV AC overhead electrification (OHE), traction substations, catenary wire tension, pantograph contact wear, transformers, and traction power feed blocks.",
  },
  {
    id: "SNT",
    name: "Signal & Telecommunication",
    code: "S&T",
    headName: "Ananya Sharma",
    email: "signal@railplan.ai",
    userCount: 98,
    activeTasks: 8,
    pendingRequests: 4,
    allocatedBudget: 18000000,
    usedBudget: 9400000,
    workforceTotal: 310,
    workforceActive: 270,
    equipmentCount: 38,
    performanceScore: 89,
    color: "#6367FF", // Electric Royal Indigo
    description: "Electronic interlocking, Kavach (TCAS) collision avoidance, point machines, track circuits, route relay interlocking, and signaling telecom.",
  },
  {
    id: "SFTY",
    name: "Safety Directorate",
    code: "SFTY",
    headName: "Devendra Yadav",
    email: "safety@railplan.ai",
    userCount: 45,
    activeTasks: 6,
    pendingRequests: 2,
    allocatedBudget: 8000000,
    usedBudget: 3400000,
    workforceTotal: 120,
    workforceActive: 105,
    equipmentCount: 15,
    performanceScore: 98,
    color: "#FB2077", // Hot Neon Rose
    description: "Safety audits, Commission of Railway Safety (CRS) compliance, accident prevention, speed restriction monitoring, and Form T/806 statutory governance.",
  },
];

export const LEGACY_MOCK_CORRIDORS: RailwayCorridor[] = [
  BHOPAL_ITARSI_CORRIDOR,
  {
    id: "WDFC-01",
    name: "Western Dedicated Freight Corridor (WDFC)",
    zone: "DFCCIL / Western Railway",
    route: "Dadri (UP) - Rewari - Palanpur - Sanand - JNPT (Navi Mumbai)",
    totalLengthKm: 1504,
    status: "ATTENTION",
    activeMaintenanceCount: 5,
    activeTrainsCount: 42,
    delayedProjectsCount: 1,
    criticalSpotsCount: 2,
    stations: [
      { name: "Dadri Junction", code: "DER", km: 0, hasActiveBlock: false, status: "NORMAL" },
      { name: "Rewari Junction", code: "RE", km: 142, hasActiveBlock: true, status: "ATTENTION" },
      { name: "Jaipur West", code: "JPW", km: 360, hasActiveBlock: false, status: "NORMAL" },
      { name: "Palanpur", code: "PNU", km: 740, hasActiveBlock: false, status: "NORMAL" },
      { name: "Vadodara South", code: "BRCY", km: 1020, hasActiveBlock: true, status: "CRITICAL" },
      { name: "JNPT Navi Mumbai", code: "JNPT", km: 1504, hasActiveBlock: false, status: "NORMAL" },
    ],
    coordinates: [
      { x: 120, y: 100 },
      { x: 180, y: 160 },
      { x: 220, y: 240 },
      { x: 260, y: 340 },
      { x: 300, y: 440 },
      { x: 340, y: 560 }
    ],
  },
  {
    id: "NDLS-MMCT",
    name: "Delhi - Mumbai Central Golden Trunk Route",
    zone: "Northern & Western Railway",
    route: "New Delhi - Mathura - Kota - Ratlam - Vadodara - Surat - Mumbai Central",
    totalLengthKm: 1384,
    status: "CRITICAL",
    activeMaintenanceCount: 8,
    activeTrainsCount: 86,
    delayedProjectsCount: 2,
    criticalSpotsCount: 3,
    stations: [
      { name: "New Delhi", code: "NDLS", km: 0, hasActiveBlock: false, status: "NORMAL" },
      { name: "Mathura Junction", code: "MTJ", km: 141, hasActiveBlock: true, status: "CRITICAL" },
      { name: "Kota Junction", code: "KOTA", km: 465, hasActiveBlock: false, status: "NORMAL" },
      { name: "Ratlam Junction", code: "RTM", km: 730, hasActiveBlock: false, status: "ATTENTION" },
      { name: "Vadodara Junction", code: "BRC", km: 991, hasActiveBlock: true, status: "MEDIUM_RISK" },
      { name: "Surat", code: "ST", km: 1120, hasActiveBlock: false, status: "NORMAL" },
      { name: "Mumbai Central", code: "MMCT", km: 1384, hasActiveBlock: false, status: "NORMAL" },
    ],
    coordinates: [
      { x: 140, y: 80 },
      { x: 170, y: 130 },
      { x: 210, y: 220 },
      { x: 250, y: 310 },
      { x: 290, y: 400 },
      { x: 310, y: 460 },
      { x: 330, y: 530 }
    ],
  },
  {
    id: "NDLS-HWH",
    name: "Delhi - Howrah Rajdhani Route",
    zone: "Northern, NCR & Eastern Railway",
    route: "New Delhi - Kanpur - Prayagraj - Pt. Deen Dayal Upadhyaya - Patna - Dhanbad - Howrah",
    totalLengthKm: 1445,
    status: "MEDIUM_RISK",
    activeMaintenanceCount: 7,
    activeTrainsCount: 94,
    delayedProjectsCount: 1,
    criticalSpotsCount: 2,
    stations: [
      { name: "New Delhi", code: "NDLS", km: 0, hasActiveBlock: false, status: "NORMAL" },
      { name: "Kanpur Central", code: "CNB", km: 440, hasActiveBlock: true, status: "MEDIUM_RISK" },
      { name: "Prayagraj Junction", code: "PRYJ", km: 635, hasActiveBlock: false, status: "NORMAL" },
      { name: "Pt. Deen Dayal Upadhyaya", code: "DDU", km: 785, hasActiveBlock: true, status: "ATTENTION" },
      { name: "Dhanbad Junction", code: "DHN", km: 1185, hasActiveBlock: false, status: "NORMAL" },
      { name: "Howrah Junction", code: "HWH", km: 1445, hasActiveBlock: false, status: "NORMAL" },
    ],
    coordinates: [
      { x: 140, y: 80 },
      { x: 280, y: 130 },
      { x: 380, y: 160 },
      { x: 470, y: 190 },
      { x: 620, y: 230 },
      { x: 740, y: 270 }
    ],
  },
  {
    id: "CSMT-MAS",
    name: "Mumbai - Chennai Mainline",
    zone: "Central & Southern Railway",
    route: "Mumbai CSMT - Pune - Solapur - Wadi - Guntakal - Renigunta - Chennai Central",
    totalLengthKm: 1281,
    status: "NORMAL",
    activeMaintenanceCount: 4,
    activeTrainsCount: 52,
    delayedProjectsCount: 0,
    criticalSpotsCount: 1,
    stations: [
      { name: "Mumbai CSMT", code: "CSMT", km: 0, hasActiveBlock: false, status: "NORMAL" },
      { name: "Pune Junction", code: "PUNE", km: 192, hasActiveBlock: false, status: "NORMAL" },
      { name: "Solapur", code: "SUR", km: 455, hasActiveBlock: false, status: "NORMAL" },
      { name: "Guntakal Junction", code: "GTL", km: 835, hasActiveBlock: true, status: "NORMAL" },
      { name: "Renigunta", code: "RU", km: 1145, hasActiveBlock: false, status: "NORMAL" },
      { name: "Chennai Central", code: "MAS", km: 1281, hasActiveBlock: false, status: "NORMAL" },
    ],
    coordinates: [
      { x: 330, y: 530 },
      { x: 370, y: 580 },
      { x: 440, y: 640 },
      { x: 540, y: 730 },
      { x: 630, y: 810 },
      { x: 680, y: 850 }
    ],
  },
  {
    id: "KONKAN-01",
    name: "Konkan Coastal Railway",
    zone: "Konkan Railway Corporation (KRCL)",
    route: "Roha - Chiplun - Ratnagiri - Madgaon (Goa) - Karwar - Udupi - Thokur (Mangaluru)",
    totalLengthKm: 741,
    status: "ATTENTION",
    activeMaintenanceCount: 6,
    activeTrainsCount: 28,
    delayedProjectsCount: 1,
    criticalSpotsCount: 2,
    stations: [
      { name: "Roha", code: "ROHA", km: 0, hasActiveBlock: false, status: "NORMAL" },
      { name: "Chiplun", code: "CHI", km: 145, hasActiveBlock: true, status: "ATTENTION" },
      { name: "Ratnagiri", code: "RN", km: 240, hasActiveBlock: false, status: "NORMAL" },
      { name: "Madgaon Junction", code: "MAO", km: 450, hasActiveBlock: false, status: "NORMAL" },
      { name: "Karwar", code: "KAWR", km: 535, hasActiveBlock: true, status: "MEDIUM_RISK" },
      { name: "Thokur", code: "TOK", km: 741, hasActiveBlock: false, status: "NORMAL" },
    ],
    coordinates: [
      { x: 320, y: 550 },
      { x: 310, y: 610 },
      { x: 300, y: 670 },
      { x: 290, y: 760 },
      { x: 300, y: 810 },
      { x: 310, y: 880 }
    ],
  },
];

export const LEGACY_MOCK_ASSETS: CorridorAsset[] = [
  ...MOCK_CORRIDOR_ASSETS,
  {
    id: "AST-SIG-204",
    name: "Multi-Aspect Colour Light Signal S-204",
    type: "SIGNAL",
    corridorId: "NDLS-MMCT",
    locationKm: "KM 148.2 (Mathura - Bharatpur Section)",
    status: "ATTENTION",
    failureRisk: 87,
    lastMaintenanceDate: "2026-07-28",
    nextRecommendedInspection: "2026-08-26",
    telemetry: {
      voltage: 108.4,
      vibration: 3.8,
      temperature: 44.2,
      cyclesCount: 14820,
    },
    departmentResponsible: "SNT",
  },
  {
    id: "AST-PNT-012",
    name: "High-Speed Point Machine PM-12 (Thick Web Switch)",
    type: "POINT_MACHINE",
    corridorId: "NDLS-MMCT",
    locationKm: "KM 152.0 (Mathura Yard Entrance)",
    status: "NORMAL",
    failureRisk: 28,
    lastMaintenanceDate: "2026-08-10",
    nextRecommendedInspection: "2026-09-10",
    telemetry: {
      voltage: 112.0,
      vibration: 1.2,
      temperature: 36.5,
      cyclesCount: 8900,
    },
    departmentResponsible: "SNT",
  },
  {
    id: "AST-OHE-088",
    name: "25kV Catenary & Contact Wire Mast OHE-CW-88",
    type: "OHE_CATENARY",
    corridorId: "NDLS-MMCT",
    locationKm: "KM 149.6 - 153.2 (Heavy Freight Gradient)",
    status: "ATTENTION",
    failureRisk: 74,
    lastMaintenanceDate: "2026-06-15",
    nextRecommendedInspection: "2026-08-25",
    telemetry: {
      voltage: 25400,
      temperature: 52.1,
      stressLevel: 215,
    },
    departmentResponsible: "ELEC",
  },
  {
    id: "AST-TRK-102",
    name: "60kg UIC Continuous Welded Rail Section (CWR-102)",
    type: "RAIL_JOINT",
    corridorId: "NDLS-MMCT",
    locationKm: "KM 148.0 - 156.0",
    status: "CRITICAL",
    failureRisk: 89,
    lastMaintenanceDate: "2026-05-12",
    nextRecommendedInspection: "2026-08-24",
    telemetry: {
      stressLevel: 310,
      vibration: 5.6,
      temperature: 46.8,
    },
    departmentResponsible: "ENG",
  },
  {
    id: "AST-TRF-004",
    name: "Traction Power Substation Transformer 25kV (TSS-04)",
    type: "TRANSFORMER",
    corridorId: "WDFC-01",
    locationKm: "KM 142.5 (Rewari Substation)",
    status: "NORMAL",
    failureRisk: 22,
    lastMaintenanceDate: "2026-07-20",
    nextRecommendedInspection: "2026-10-20",
    telemetry: {
      voltage: 25100,
      temperature: 64.0,
      stressLevel: 140,
    },
    departmentResponsible: "ELEC",
  },
  {
    id: "AST-BRG-007",
    name: "Major Yamuna River Bridge Pier 7 & Girders",
    type: "BRIDGE_PIER",
    corridorId: "NDLS-HWH",
    locationKm: "KM 441.8 (Kanpur Section)",
    status: "ATTENTION",
    failureRisk: 68,
    lastMaintenanceDate: "2026-06-02",
    nextRecommendedInspection: "2026-08-30",
    telemetry: {
      stressLevel: 195,
      vibration: 2.9,
    },
    departmentResponsible: "ENG",
  },
];

export const MOCK_SERVICE_REQUESTS: ServiceRequest[] = [
  {
    id: "SR-1042",
    title: "25kV OHE Power Block & Catenary Tensioning Support for Track Relay",
    requestingDepartment: "ENG",
    targetDepartment: "ELEC",
    corridorId: "NDLS-MMCT",
    locationKm: "KM 148.0 - 154.0 (Mathura Section)",
    requestType: "Electrical Support",
    priority: "HIGH",
    description: "Engineering department is scheduled for heavy 60kg rail renewal and sleeper replacement between KM 148 and KM 154. Urgent 25kV OHE power isolation (block window of 4 hours), neutral section checking, and post-track-lift catenary readjustment is required from the Electrical department to avoid pantograph entanglement.",
    requiredDate: "2026-08-28",
    submissionDate: "2026-08-22",
    completionDeadline: "2026-08-30",
    status: "UNDER_REVIEW",
    estimatedCost: 402000,
    costBreakdown: {
      labour: 120000,
      equipment: 80000,
      material: 150000,
      logistics: 25000,
      trackBlock: 0,
      contingency: 27000,
      totalEstimated: 402000,
      actualCost: 0,
    },
    resourcesRequired: [
      "1x 25kV OHE Tower Wagon",
      "2x Traction Linemen Crews (8 technicians)",
      "1x Portable Earthing Discharge Rod Set",
      "1x High-Accuracy Laser Catenary Height Gauge"
    ],
    attachments: [
      "Track_Geometry_Inspection_Report_KM148.pdf",
      "OHE_Clearance_Drawing_Sec4.dwg"
    ],
    additionalNotes: "Traffic block requested during 01:30 AM to 05:30 AM low-traffic window to minimize impact on 12952 Mumbai Rajdhani Express.",
    progress: 0,
    assignedToDepartment: "ELEC",
    centralAdminComments: "",
    aiRiskScore: 87,
    aiRecommendedPriority: "HIGH",
    aiRationale: "High probability of catenary tension misalignment if track is lifted by 45mm without simultaneous OHE adjustment. Recommended approval within 48h.",
    progressUpdates: [],
    history: [
      {
        timestamp: "2026-08-22 10:30 AM",
        actor: "Vikram Singh (Engineering)",
        action: "Created and submitted Service Request SR-1042 for Electrical Support.",
        note: "Submitted with high priority due to upcoming track relay window."
      }
    ],
  },
  {
    id: "SR-1040",
    title: "Urgent Interlocking Point Machine Re-alignment & Signal S-204 Calibration",
    requestingDepartment: "SNT",
    targetDepartment: "ENG",
    corridorId: "NDLS-MMCT",
    locationKm: "KM 152.0 (Mathura Yard)",
    requestType: "Signal Support",
    priority: "CRITICAL",
    description: "Point machine PM-12 throwing intermittent out-of-correspondence alarms. Track civil sleeper packing and turnout switch tongue alignment needed before signal lock can be certified.",
    requiredDate: "2026-08-25",
    submissionDate: "2026-08-21",
    completionDeadline: "2026-08-27",
    status: "APPROVED",
    estimatedCost: 285000,
    costBreakdown: {
      labour: 95000,
      equipment: 65000,
      material: 85000,
      logistics: 15000,
      trackBlock: 0,
      contingency: 25000,
      totalEstimated: 285000,
      actualCost: 120000,
    },
    resourcesRequired: [
      "1x Point Gauge Calibration Kit",
      "1x Track Tie Tamping Gang (6 staff)"
    ],
    progress: 50,
    assignedToDepartment: "ENG",
    centralAdminComments: "Approved. Prioritize turnout stability before weekend festival traffic.",
    aiRiskScore: 92,
    aiRecommendedPriority: "CRITICAL",
    aiRationale: "Turnout switch failure at Mathura Yard would delay up to 24 passenger trains including Vande Bharat.",
    progressUpdates: [
      {
        timestamp: "2026-08-22 02:15 PM",
        updatedBy: "Vikram Singh (Engineering)",
        department: "ENG",
        percentage: 50,
        notes: "Turnout sleeper packing completed. Switch tongue clearance measured at 115mm. Handing over to S&T for final lock test.",
      }
    ],
    history: [
      {
        timestamp: "2026-08-21 09:15 AM",
        actor: "Ananya Sharma (Signal & Telecom)",
        action: "Submitted Request SR-1040.",
      },
      {
        timestamp: "2026-08-21 11:45 AM",
        actor: "Rajesh Verma (Central Admin)",
        action: "Approved request and assigned to Engineering Department.",
      },
      {
        timestamp: "2026-08-22 02:15 PM",
        actor: "Vikram Singh (Engineering)",
        action: "Updated progress to 50%.",
      }
    ],
  },
  {
    id: "SR-1038",
    title: "Deployment of Plasser 09-3X Duomatic Tamping Machine for CWR Consolidation",
    requestingDepartment: "ENG",
    targetDepartment: "ENG",
    corridorId: "WDFC-01",
    locationKm: "KM 140.0 - 175.0 (Rewari - Ateli Section)",
    requestType: "Equipment Request",
    priority: "MEDIUM",
    description: "Deep screening of ballast completed on WDFC Up line. Heavy machine tamping and Dynamic Track Stabilizer (DTS) required for 35km stretch to restore 100 kmph freight speed.",
    requiredDate: "2026-09-02",
    submissionDate: "2026-08-20",
    completionDeadline: "2026-09-08",
    status: "ASSIGNED",
    estimatedCost: 650000,
    costBreakdown: {
      labour: 180000,
      equipment: 320000,
      material: 50000,
      logistics: 60000,
      trackBlock: 0,
      contingency: 40000,
      totalEstimated: 650000,
      actualCost: 150000,
    },
    resourcesRequired: [
      "1x Plasser 09-3X Duomatic Tamping Machine",
      "1x Dynamic Track Stabilizer (DTS)",
      "2x Machine Operators + 1 Maintenance Engineer"
    ],
    progress: 25,
    assignedToDepartment: "ENG",
    centralAdminComments: "Assigned. Machine TM-04 allocated from Rewari Depot.",
    aiRiskScore: 45,
    aiRecommendedPriority: "MEDIUM",
    progressUpdates: [
      {
        timestamp: "2026-08-22 11:00 AM",
        updatedBy: "Sunil Deshmukh (Civil)",
        department: "ENG",
        percentage: 25,
        notes: "Machine TM-04 mobilized to Rewari siding. Pre-run calibration in progress.",
      }
    ],
    history: [
      {
        timestamp: "2026-08-20 03:00 PM",
        actor: "Sunil Deshmukh (Civil)",
        action: "Submitted Request SR-1038.",
      },
      {
        timestamp: "2026-08-21 04:30 PM",
        actor: "Rajesh Verma (Central Admin)",
        action: "Approved and assigned to Civil Engineering Directorate.",
      }
    ],
  },
  {
    id: "SR-1035",
    title: "Ultrasonic Axle & Bogie Safety Inspection on Vande Bharat Rake 22",
    requestingDepartment: "MECH",
    targetDepartment: "SFTY",
    corridorId: "NDLS-HWH",
    locationKm: "Kanpur Loco & Coach Care Facility",
    requestType: "Safety Inspection",
    priority: "HIGH",
    description: "Periodic 180-day non-destructive testing (NDT) and wheel profile laser measurement on Vande Bharat Express Rake 22 following high-speed run.",
    requiredDate: "2026-08-24",
    submissionDate: "2026-08-19",
    completionDeadline: "2026-08-24",
    status: "COMPLETED",
    estimatedCost: 180000,
    costBreakdown: {
      labour: 80000,
      equipment: 50000,
      material: 20000,
      logistics: 10000,
      trackBlock: 0,
      contingency: 20000,
      totalEstimated: 180000,
      actualCost: 172000,
    },
    resourcesRequired: [
      "1x Digital Ultrasonic Flaw Detector",
      "2x Certified NDT Level-III Safety Inspectors"
    ],
    progress: 100,
    assignedToDepartment: "SFTY",
    centralAdminComments: "Inspection completed. All 16 motor and trailer coach wheelsets certified within safety tolerances.",
    aiRiskScore: 30,
    aiRecommendedPriority: "HIGH",
    progressUpdates: [
      {
        timestamp: "2026-08-23 04:00 PM",
        updatedBy: "Devendra Yadav (Safety)",
        department: "SFTY",
        percentage: 100,
        notes: "Full ultrasonic scan complete. No sub-surface fatigue cracks found. Fitness certificate issued.",
      }
    ],
    history: [
      {
        timestamp: "2026-08-19 10:00 AM",
        actor: "Sunil Deshmukh (Civil)",
        action: "Submitted Request SR-1035.",
      },
      {
        timestamp: "2026-08-19 02:00 PM",
        actor: "Rajesh Verma (Central Admin)",
        action: "Approved and assigned to Safety Department.",
      },
      {
        timestamp: "2026-08-23 04:00 PM",
        actor: "Devendra Yadav (Safety)",
        action: "Marked work 100% complete and submitted safety report.",
      }
    ],
  },
  {
    id: "SR-1031",
    title: "Civil Foundation Rehabilitation for Traction Substation TSS-04",
    requestingDepartment: "ELEC",
    targetDepartment: "ENG",
    corridorId: "WDFC-01",
    locationKm: "KM 142.5 (Rewari Substation)",
    requestType: "Track Repair",
    priority: "MEDIUM",
    description: "Settlement observed near 25kV power transformer plinth due to heavy monsoon drainage runoff. Reinforced concrete underpinning and retaining wall reinforcement required.",
    requiredDate: "2026-08-20",
    submissionDate: "2026-08-15",
    completionDeadline: "2026-08-22",
    status: "CLOSED",
    estimatedCost: 320000,
    costBreakdown: {
      labour: 110000,
      equipment: 70000,
      material: 100000,
      logistics: 20000,
      trackBlock: 0,
      contingency: 20000,
      totalEstimated: 320000,
      actualCost: 310000,
    },
    resourcesRequired: [
      "Civil Masonry Gang (10 staff)",
      "Ready-Mix Concrete Mixer & Pump"
    ],
    progress: 100,
    assignedToDepartment: "ENG",
    centralAdminComments: "Verified and closed by Central Admin.",
    aiRiskScore: 25,
    progressUpdates: [],
    history: [
      {
        timestamp: "2026-08-15 11:00 AM",
        actor: "K. Ramanathan (Electrical)",
        action: "Submitted Request SR-1031.",
      },
      {
        timestamp: "2026-08-16 10:00 AM",
        actor: "Rajesh Verma (Central Admin)",
        action: "Approved and assigned to Engineering.",
      },
      {
        timestamp: "2026-08-21 05:00 PM",
        actor: "Vikram Singh (Engineering)",
        action: "Work completed 100%.",
      },
      {
        timestamp: "2026-08-22 09:30 AM",
        actor: "Rajesh Verma (Central Admin)",
        action: "Verified inspection certificate and marked request as CLOSED.",
      }
    ],
  },
];

export const MOCK_MAINTENANCE_TASKS: MaintenanceTask[] = [
  {
    id: "MT-101",
    title: "Periodic Ultrasonic Rail Flaw Detection (USFD) Scan",
    assetId: "AST-TRK-102",
    assetName: "60kg UIC Continuous Welded Rail Section (CWR-102)",
    assetType: "Track Rails & Welds",
    corridorId: "NDLS-MMCT",
    locationKm: "KM 148.0 - 156.0",
    departmentId: "ENG",
    maintenanceType: "USFD Ultrasonic Scan",
    lastInspectionDate: "2026-05-12",
    riskScore: 89,
    recommendedDate: "2026-08-24",
    estimatedDurationHours: 4,
    estimatedCost: 145000,
    status: "OVERDUE",
    progress: 0,
    assignedTeam: "Delhi Div USFD Team-2",
    requiredResources: ["USFD Digital Flaw Detector", "Track Safety Escort Trolley"],
  },
  {
    id: "MT-102",
    title: "Catenary Sag Adjustment & Dropper Tensioning",
    assetId: "AST-OHE-088",
    assetName: "25kV Catenary & Contact Wire Mast OHE-CW-88",
    assetType: "OHE Catenary System",
    corridorId: "NDLS-MMCT",
    locationKm: "KM 149.6 - 153.2",
    departmentId: "ELEC",
    maintenanceType: "Preventive",
    lastInspectionDate: "2026-06-15",
    riskScore: 74,
    recommendedDate: "2026-08-28",
    estimatedDurationHours: 4,
    estimatedCost: 210000,
    status: "SCHEDULED",
    progress: 0,
    assignedTeam: "Mathura Traction Crew A",
    requiredResources: ["OHE Tower Wagon TW-08", "Catenary Height Gauge"],
  },
  {
    id: "MT-103",
    title: "Electronic Interlocking Relay Logic & Point Machine Overhaul",
    assetId: "AST-PNT-012",
    assetName: "High-Speed Point Machine PM-12",
    assetType: "Signalling Point Machine",
    corridorId: "NDLS-MMCT",
    locationKm: "KM 152.0",
    departmentId: "SNT",
    maintenanceType: "Periodic Overhaul",
    lastInspectionDate: "2026-08-10",
    riskScore: 65,
    recommendedDate: "2026-08-27",
    estimatedDurationHours: 3,
    estimatedCost: 175000,
    status: "IN_PROGRESS",
    progress: 40,
    assignedTeam: "Mathura S&T Gang-1",
    requiredResources: ["Point Calibration Kit", "Multimeter Loggers"],
  },
  {
    id: "MT-104",
    title: "Yamuna Bridge Girder Anti-Corrosion Epoxy Coating & Bearing Greasing",
    assetId: "AST-BRG-007",
    assetName: "Major Yamuna River Bridge Pier 7 & Girders",
    assetType: "Steel Girders & Piers",
    corridorId: "NDLS-HWH",
    locationKm: "KM 441.8",
    departmentId: "ENG",
    maintenanceType: "Preventive",
    lastInspectionDate: "2026-06-02",
    riskScore: 68,
    recommendedDate: "2026-08-30",
    estimatedDurationHours: 6,
    estimatedCost: 480000,
    status: "SCHEDULED",
    progress: 0,
    assignedTeam: "Kanpur Bridge Gang",
    requiredResources: ["Hydro-Jetting Rig", "Epoxy Paint Sprayers", "Safety Harnesses"],
  },
  {
    id: "MT-105",
    title: "Traction Substation 25kV Circuit Breaker SF6 Gas Pressure Test",
    assetId: "AST-TRF-004",
    assetName: "Traction Substation Transformer 25kV (TSS-04)",
    assetType: "Power Substation",
    corridorId: "WDFC-01",
    locationKm: "KM 142.5",
    departmentId: "ELEC",
    maintenanceType: "Preventive",
    lastInspectionDate: "2026-07-20",
    riskScore: 22,
    recommendedDate: "2026-09-15",
    estimatedDurationHours: 3,
    estimatedCost: 90000,
    status: "SCHEDULED",
    progress: 0,
    assignedTeam: "Rewari Power Team",
    requiredResources: ["SF6 Gas Analyzer", "Dielectric Oil Tester"],
  },
  {
    id: "MT-106",
    title: "Deep Screening & Ballast Cleaning Machine (BCM) Operation",
    assetId: "AST-TRK-102",
    assetName: "Track Ballast Bed Section 14",
    assetType: "Permanent Way Ballast",
    corridorId: "WDFC-01",
    locationKm: "KM 140.0 - 165.0",
    departmentId: "ENG",
    maintenanceType: "Corrective",
    lastInspectionDate: "2026-07-05",
    riskScore: 58,
    recommendedDate: "2026-09-05",
    estimatedDurationHours: 8,
    estimatedCost: 820000,
    status: "SCHEDULED",
    progress: 0,
    assignedTeam: "Track Machine Division 3",
    requiredResources: ["Plasser BCM Machine", "Muck Disposal Wagon rake"],
  },
];

export const MOCK_BUNDLES: BundledMaintenanceOrder[] = [
  {
    id: "BND-101",
    title: "Delhi - Mumbai Golden Trunk Joint Mega Block (KM 148.0 - 156.0)",
    corridorId: "NDLS-MMCT",
    locationKm: "KM 148.0 - 156.0 (Mathura - Bharatpur Section)",
    taskIds: ["MT-101", "MT-102", "MT-103"],
    tasksSummary: [
      {
        id: "MT-101",
        title: "Periodic Ultrasonic Rail Flaw Detection (USFD) Scan",
        departmentId: "ENG",
        durationHours: 4,
        cost: 145000,
      },
      {
        id: "MT-102",
        title: "Catenary Sag Adjustment & Dropper Tensioning",
        departmentId: "ELEC",
        durationHours: 4,
        cost: 210000,
      },
      {
        id: "MT-103",
        title: "Electronic Interlocking Relay Logic & Point Machine Overhaul",
        departmentId: "SNT",
        durationHours: 3,
        cost: 175000,
      },
    ],
    scheduledDate: "2026-08-28",
    timeWindow: "01:30 AM - 06:00 AM (Single Night Mega Block)",
    individualHoursSum: 11.0,
    bundledBlockHours: 4.5,
    timeSavedHours: 6.5,
    timeReductionPercent: 35,
    trainsDelaySavedMinutes: 240,
    financialSavingsINR: 185000,
    participatingDepartments: ["ENG", "ELEC", "SNT"],
    status: "APPROVED",
    aiBundlingRationale: "Spatio-temporal clustering of 3 tasks on the same 8km section. Synchronizing 25kV traction shutdown with track civil lifting and signal point testing saves 6.5 hours of track closure time and prevents 240 minutes of delay across 14 Rajdhani and express trains.",
  },
  {
    id: "BND-102",
    title: "WDFC Heavy Freight Joint Track & Substation Block",
    corridorId: "WDFC-01",
    locationKm: "KM 140.0 - 165.0 (Rewari Section)",
    taskIds: ["MT-106", "MT-105"],
    tasksSummary: [
      {
        id: "MT-106",
        title: "Deep Screening & Ballast Cleaning Machine (BCM) Operation",
        departmentId: "ENG",
        durationHours: 8,
        cost: 820000,
      },
      {
        id: "MT-105",
        title: "Traction Substation 25kV Circuit Breaker SF6 Gas Pressure Test",
        departmentId: "ELEC",
        durationHours: 3,
        cost: 90000,
      },
    ],
    scheduledDate: "2026-09-05",
    timeWindow: "00:00 AM - 08:00 AM (Off-Peak Freight Window)",
    individualHoursSum: 11.0,
    bundledBlockHours: 8.0,
    timeSavedHours: 3.0,
    timeReductionPercent: 27,
    trainsDelaySavedMinutes: 310,
    financialSavingsINR: 320000,
    participatingDepartments: ["ENG", "ELEC"],
    status: "PROPOSED",
    aiBundlingRationale: "Bundling ballast deep screening with electrical substation maintenance eliminates duplicate freight speed restrictions and saves ₹3.2 Lakhs in demurrage.",
  },
];

export const MOCK_RESOURCES: ResourceItem[] = [
  {
    id: "RES-EQP-01",
    name: "Plasser & Theurer 09-3X Dynamic Tamping Machine (TM-04)",
    category: "EQUIPMENT",
    type: "Heavy Track Machine",
    departmentId: "ENG",
    assignedCorridor: "WDFC-01",
    status: "AVAILABLE",
    healthOrSkillLevel: "98% Health (Calibration Certified)",
    utilizationRate: 78,
    operatorOrLead: "S. K. Verma (Senior Master Operator)",
  },
  {
    id: "RES-EQP-02",
    name: "25kV AC Self-Propelled OHE Inspection Car / Tower Wagon (TW-08)",
    category: "EQUIPMENT",
    type: "Electrical Traction Vehicle",
    departmentId: "ELEC",
    assignedCorridor: "NDLS-MMCT",
    status: "ASSIGNED",
    currentTask: "SR-1042 / Mathura Power Block",
    healthOrSkillLevel: "94% Health (Hydraulic Lift Certified)",
    utilizationRate: 92,
    operatorOrLead: "P. Murthy (Traction Engineer)",
  },
  {
    id: "RES-EQP-03",
    name: "Digital Continuous USFD Rail Testing Vehicle (USFD-Car-02)",
    category: "EQUIPMENT",
    type: "Ultrasonic Flaw Scanner",
    departmentId: "ENG",
    assignedCorridor: "NDLS-MMCT",
    status: "AVAILABLE",
    healthOrSkillLevel: "100% Calibrated (RDSO Standard)",
    utilizationRate: 84,
    operatorOrLead: "D. Ganguly (NDT Specialist)",
  },
  {
    id: "RES-EQP-04",
    name: "140-Tonne Gottwald Heavy Breakdown Crane (CR-01)",
    category: "EQUIPMENT",
    type: "Emergency Recovery Crane",
    departmentId: "SFTY",
    assignedCorridor: "NDLS-HWH",
    status: "AVAILABLE",
    healthOrSkillLevel: "100% Operational (Emergency Standby)",
    utilizationRate: 20,
    operatorOrLead: "M. K. Pandey (Crane Pilot)",
  },
  {
    id: "RES-WRK-01",
    name: "Permanent Way Track Renewal Gang Alpha (24 Trackmen)",
    category: "WORKFORCE",
    type: "Heavy Civil Track Crew",
    departmentId: "ENG",
    assignedCorridor: "NDLS-MMCT",
    status: "ASSIGNED",
    currentTask: "Track Renewal KM 148-154",
    healthOrSkillLevel: "Class A certified (Rail Welds & CWR)",
    utilizationRate: 95,
    operatorOrLead: "Rameshwar Prasad (Supervisor)",
  },
  {
    id: "RES-WRK-02",
    name: "25kV OHE High-Tension Linemen Squad (12 Linemen)",
    category: "WORKFORCE",
    type: "Electrical Traction Squad",
    departmentId: "ELEC",
    assignedCorridor: "NDLS-MMCT",
    status: "AVAILABLE",
    healthOrSkillLevel: "High Voltage 25kV Live-Line Certified",
    utilizationRate: 88,
    operatorOrLead: "N. Selvam (Senior OHE In-Charge)",
  },
  {
    id: "RES-WRK-03",
    name: "Electronic Interlocking & Kavach TCAS Testing Engineers (6 Engineers)",
    category: "WORKFORCE",
    type: "Specialized S&T Engineers",
    departmentId: "SNT",
    assignedCorridor: "NDLS-MMCT",
    status: "AVAILABLE",
    healthOrSkillLevel: "RDSO Level-4 Interlocking Certified",
    utilizationRate: 82,
    operatorOrLead: "Rohit Agarwal (Lead Signal Specialist)",
  },
  {
    id: "RES-WRK-04",
    name: "Commission of Railway Safety Audit Inspection Team (4 Officers)",
    category: "WORKFORCE",
    type: "Safety Directorate Inspectors",
    departmentId: "SFTY",
    assignedCorridor: "NDLS-HWH",
    status: "AVAILABLE",
    healthOrSkillLevel: "Chief Safety Officer Clearance",
    utilizationRate: 65,
    operatorOrLead: "Dr. K. L. Srivastava",
  },
];

export const MOCK_AI_RECOMMENDATIONS: AiRecommendation[] = [
  {
    id: "REC-AI-01",
    title: "Combine Track Renewal MT-101 and Catenary Sag MT-102 into Single 4-Hour Block Window",
    description: "Track inspection and OHE dropper tensioning are both scheduled between KM 148 and KM 154 within 4 days of each other. Merging them into a synchronized joint block on 28 August reduces cumulative track closure by 30% and saves 180 minutes of passenger train delay.",
    departmentId: "ENG",
    corridorId: "NDLS-MMCT",
    riskScore: 88,
    confidenceScore: 95,
    reason: "Spatio-temporal clustering of maintenance tasks on the same 6km track section. Joint execution eliminates duplicate speed restrictions.",
    suggestedAction: "Execute joint block window during 01:30 AM - 05:30 AM night slot.",
    estimatedCostImpact: -185000,
    estimatedDelayReductionMinutes: 180,
    status: "PENDING",
    createdAt: "2026-08-23 08:00 AM",
  },
  {
    id: "REC-AI-02",
    title: "High Probability of Signal S-204 Relay Failure Detected (87% Risk within 14 Days)",
    description: "Telemetry analysis from Mathura Yard reveals thermal micro-fluctuations (44.2°C) and coil voltage drops in Signal S-204 lamp transformer. Immediate preventive capacitor replacement recommended before upcoming festival peak traffic.",
    departmentId: "SNT",
    corridorId: "NDLS-MMCT",
    riskScore: 87,
    confidenceScore: 92,
    reason: "Component age 4.8 years, vibration index exceeding threshold by 24%, thermal cycle degradation signature matching historical failure pattern.",
    suggestedAction: "Dispatch S&T quick-response team with replacement electronic relay unit.",
    estimatedCostImpact: -45000,
    estimatedDelayReductionMinutes: 240,
    status: "PENDING",
    createdAt: "2026-08-23 09:30 AM",
  },
  {
    id: "REC-AI-03",
    title: "Reschedule Heavy Freight Tamping on WDFC to 02:00 AM Low-Traffic Slot",
    description: "Tamping task MT-106 originally scheduled at 14:00 PM conflicts with 6 double-stack container rakes from Mundra Port. Shifting by 12 hours eliminates freight congestion and avoids ₹3.2L demurrage costs.",
    departmentId: "OPS",
    corridorId: "WDFC-01",
    riskScore: 42,
    confidenceScore: 98,
    reason: "Dynamic freight timetable simulation indicates zero traffic throughput bottleneck between 02:00 AM and 06:00 AM.",
    suggestedAction: "Reschedule block window approval in Operations portal.",
    estimatedCostImpact: -320000,
    estimatedDelayReductionMinutes: 310,
    status: "PENDING",
    createdAt: "2026-08-23 11:15 AM",
  },
  {
    id: "REC-AI-04",
    title: "Pre-Monsoon Culvert & Pier Scour Depth Monitoring on Yamuna Bridge",
    description: "Sonar telemetry indicates minor silt displacement around Pier 7 (KM 441.8). Preventive geo-textile bag pitching recommended before river discharge peaks.",
    departmentId: "ENG",
    corridorId: "NDLS-HWH",
    riskScore: 68,
    confidenceScore: 89,
    reason: "Hydrodynamic river telemetry and seasonal monsoon flood model projection.",
    suggestedAction: "Issue maintenance work order for bridge engineering diving squad.",
    estimatedCostImpact: -120000,
    estimatedDelayReductionMinutes: 90,
    status: "PENDING",
    createdAt: "2026-08-23 12:00 PM",
  },
];

export const MOCK_NOTIFICATIONS: NotificationItem[] = [
  {
    id: "NOTIF-01",
    title: "New Service Request SR-1042 Submitted",
    message: "Engineering Department has submitted a request for Electrical OHE Support on NDLS-MMCT (KM 148-154).",
    type: "INFO",
    timestamp: "10 mins ago",
    read: false,
    departmentId: "ALL",
    linkHref: "/central/approvals",
  },
  {
    id: "NOTIF-02",
    title: "AI Risk Alert: Signal S-204 Failure Risk 87%",
    message: "AI Predictive Engine detected imminent relay degradation in Mathura Yard within 14 days.",
    type: "CRITICAL",
    timestamp: "45 mins ago",
    read: false,
    departmentId: "SNT",
    linkHref: "/department/ai-insights",
  },
  {
    id: "NOTIF-03",
    title: "Service Request SR-1040 Approved & Assigned",
    message: "Central Admin approved Turnout Point Alignment and assigned task to Engineering Department.",
    type: "SUCCESS",
    timestamp: "2 hours ago",
    read: true,
    departmentId: "ENG",
    linkHref: "/department/requests",
  },
  {
    id: "NOTIF-04",
    title: "Vande Bharat Safety Inspection SR-1035 Completed",
    message: "Safety Department has marked ultrasonic wheelset inspection complete. Certificate attached.",
    type: "SUCCESS",
    timestamp: "4 hours ago",
    read: true,
    departmentId: "MECH",
    linkHref: "/department/tasks",
  },
  {
    id: "NOTIF-05",
    title: "Maintenance Task MT-101 Overdue Notice",
    message: "Ultrasonic Rail Flaw Detection (USFD) on Delhi-Mumbai corridor is past recommended date.",
    type: "WARNING",
    timestamp: "6 hours ago",
    read: false,
    departmentId: "ENG",
    linkHref: "/department/tasks",
  },
];

export const MOCK_AUDIT_LOGS: AuditLogEntry[] = [
  {
    id: "AUD-1092",
    timestamp: "2026-08-23 11:10 AM",
    user: "Rajesh Verma",
    department: "Central Control Authority",
    action: "Assigned Service Request",
    entityId: "SR-1040",
    previousStatus: "APPROVED",
    newStatus: "ASSIGNED",
    details: "Assigned point machine turnout civil alignment to Engineering Department.",
  },
  {
    id: "AUD-1091",
    timestamp: "2026-08-23 11:00 AM",
    user: "Rajesh Verma",
    department: "Central Control Authority",
    action: "Approved Service Request",
    entityId: "SR-1040",
    previousStatus: "UNDER_REVIEW",
    newStatus: "APPROVED",
    details: "Approved with condition: allocate electrical team within 48h.",
  },
  {
    id: "AUD-1090",
    timestamp: "2026-08-23 10:45 AM",
    user: "Rajesh Verma",
    department: "Central Control Authority",
    action: "Changed Priority",
    entityId: "SR-1040",
    previousStatus: "HIGH",
    newStatus: "CRITICAL",
    details: "Elevated priority based on AI high-speed corridor risk score (92%).",
  },
  {
    id: "AUD-1089",
    timestamp: "2026-08-23 10:30 AM",
    user: "Vikram Singh",
    department: "Engineering Department",
    action: "Created Service Request",
    entityId: "SR-1042",
    previousStatus: "DRAFT",
    newStatus: "SUBMITTED",
    details: "Engineering Department submitted Request SR-1042 for Electrical OHE power block.",
  },
  {
    id: "AUD-1088",
    timestamp: "2026-08-22 05:30 PM",
    user: "Devendra Yadav",
    department: "Safety Department",
    action: "Uploaded Safety Certification",
    entityId: "SR-1035",
    previousStatus: "IN_PROGRESS",
    newStatus: "COMPLETED",
    details: "Completed NDT ultrasonic inspection on Vande Bharat Rake 22. Fitness certified.",
  },
  {
    id: "AUD-1087",
    timestamp: "2026-08-22 09:30 AM",
    user: "Rajesh Verma",
    department: "Central Control Authority",
    action: "Verified & Closed Request",
    entityId: "SR-1031",
    previousStatus: "COMPLETED",
    newStatus: "CLOSED",
    details: "Final civil inspection sign-off completed for Rewari Substation plinth.",
  },
];
