import {
  RailwayCorridor,
  CorridorAsset,
  LiveTrain,
  MaintenanceBlockRequest,
  StatutoryT806Sanction,
  UserProfile,
  DepartmentId
} from "./types";

// ==========================================
// 1. BHOPAL - ITARSI (BPL-ET) 120 KM CORRIDOR
// ==========================================
export const BHOPAL_ITARSI_CORRIDOR: RailwayCorridor = {
  id: "BPL-ET",
  name: "Bhopal - Itarsi High-Density Trunk Corridor (120 KM)",
  zone: "West Central Railway (WCR)",
  route: "Bhopal Jn - Rani Kamlapati - Mandideep - Obaidullaganj - Barkhera - Budni - Narmadapuram - Itarsi Jn",
  totalLengthKm: 120,
  status: "ATTENTION",
  activeMaintenanceCount: 7,
  activeTrainsCount: 15,
  delayedProjectsCount: 1,
  criticalSpotsCount: 2,
  stations: [
    { name: "Bhopal Junction", code: "BPL", km: 0, hasActiveBlock: false, status: "NORMAL", platformsCount: 6, interlockingType: "Solid State Interlocking (SSI)", lat: 23.2599, lng: 77.4126 },
    { name: "Rani Kamlapati", code: "RKMP", km: 6, hasActiveBlock: false, status: "NORMAL", platformsCount: 5, interlockingType: "Electronic Interlocking (EI)", lat: 23.2205, lng: 77.4398 },
    { name: "Mandideep (Industrial Hub)", code: "MDDP", km: 24, hasActiveBlock: true, status: "ATTENTION", platformsCount: 3, interlockingType: "Route Relay Interlocking (RRI)", lat: 23.0760, lng: 77.5180 },
    { name: "Obaidullaganj", code: "ODG", km: 38, hasActiveBlock: false, status: "NORMAL", platformsCount: 2, interlockingType: "Electronic Interlocking (EI)", lat: 22.9830, lng: 77.5850 },
    { name: "Barkhera (Ghat Section Entry)", code: "BKA", km: 56, hasActiveBlock: true, status: "CRITICAL", platformsCount: 3, interlockingType: "Electronic Interlocking (EI) + Kavach", lat: 22.8650, lng: 77.6200 },
    { name: "Budni (Mid-Ghat Section)", code: "BNI", km: 78, hasActiveBlock: true, status: "CRITICAL", platformsCount: 3, interlockingType: "Automatic Block Signalling (ABS)", lat: 22.7800, lng: 77.6800 },
    { name: "Narmadapuram (Hoshangabad)", code: "NDPM", km: 96, hasActiveBlock: false, status: "NORMAL", platformsCount: 4, interlockingType: "Electronic Interlocking (EI)", lat: 22.7519, lng: 77.7277 },
    { name: "Itarsi Junction (Central Hub)", code: "ET", km: 120, hasActiveBlock: false, status: "NORMAL", platformsCount: 8, interlockingType: "Central Route Relay Interlocking", lat: 22.6133, lng: 77.7600 },
  ],
  coordinates: [
    { x: 350, y: 260 },
    { x: 353, y: 270 },
    { x: 356, y: 285 },
    { x: 358, y: 298 },
    { x: 362, y: 312 },
    { x: 365, y: 325 },
    { x: 368, y: 338 },
    { x: 370, y: 350 },
  ],
  geoCoordinates: [
    [23.2599, 77.4126],
    [23.2205, 77.4398],
    [23.0760, 77.5180],
    [22.9830, 77.5850],
    [22.8650, 77.6200],
    [22.7800, 77.6800],
    [22.7519, 77.7277],
    [22.6133, 77.7600],
  ],
};

// ==========================================
// 2. 130 ASSETS & TELEMETRY
// 50 Track + 50 OHE + 30 Signal/Kavach
// ==========================================
export function generateCorridorAssets(): CorridorAsset[] {
  const assets: CorridorAsset[] = [];

  // A. 50 Track Segments: TRK-BPL-101 to TRK-BPL-150 (KM 0.8 to 119.2)
  for (let i = 1; i <= 50; i++) {
    const idNum = 100 + i;
    const km = Number((0.8 + (i - 1) * 2.38).toFixed(1));
    const isBarkheraBudni = km >= 54 && km <= 80;
    const isMandideep = km >= 22 && km <= 26;

    // Realistic telemetry profiles
    const railTemp = isBarkheraBudni 
      ? Number((54.5 + Math.random() * 6.5).toFixed(1)) 
      : Number((38.0 + Math.random() * 8.0).toFixed(1));

    const vibration = isBarkheraBudni
      ? Number((4.5 + Math.random() * 3.2).toFixed(2))
      : Number((1.5 + Math.random() * 1.8).toFixed(2));

    const gaugeDev = isBarkheraBudni
      ? Number((4.2 + Math.random() * 3.6).toFixed(1))
      : Number((-1.2 + Math.random() * 3.2).toFixed(1));

    const tqi = isBarkheraBudni ? Math.floor(42 + Math.random() * 14) : Math.floor(22 + Math.random() * 12);
    
    // Dynamic risk score (0 - 100%)
    let risk = Math.min(100, Math.floor(
      (railTemp > 50 ? (railTemp - 50) * 4 : 0) +
      (vibration > 4.0 ? (vibration - 4.0) * 12 : 0) +
      (Math.abs(gaugeDev) > 4.0 ? (Math.abs(gaugeDev) - 4.0) * 10 : 0) +
      (tqi > 36 ? (tqi - 36) * 1.8 : 8) +
      (isBarkheraBudni ? 25 : 5)
    ));
    if (i === 24) risk = 92; // Specifically critical spot at Barkhera Ghat KM 56.4
    if (i === 11) risk = 78; // Mandideep Yard transition

    const status = risk >= 80 ? "CRITICAL" : risk >= 50 ? "ATTENTION" : "NORMAL";

    assets.push({
      id: `TRK-BPL-${idNum}`,
      name: `60kg UIC Track Segment #${idNum} (${km < 6 ? "Bhopal Outer" : km < 56 ? "Mid Section" : km < 80 ? "Vindhyachal Ghat" : "Itarsi Approach"})`,
      type: "RAIL_JOINT",
      corridorId: "BPL-ET",
      locationKm: `KM ${km.toFixed(1)} (${km % 2 === 0 ? "Up Line" : "Down Line"})`,
      status,
      failureRisk: risk,
      lastMaintenanceDate: "2026-07-14",
      nextRecommendedInspection: "2026-09-28",
      telemetry: {
        railTemperature: railTemp,
        temperature: railTemp,
        vibrationAmplitude: vibration,
        vibration: vibration,
        trackGeometryGaugeDeviation: gaugeDev,
        tqiScore: tqi,
        stressLevel: Math.floor(180 + vibration * 25),
        dynamicRiskScore: risk,
      },
      departmentResponsible: "ENG",
    });
  }

  // B. 50 OHE Portals: OHE-ET-201 to OHE-ET-250 (KM 1.2 to 119.5)
  for (let i = 1; i <= 50; i++) {
    const idNum = 200 + i;
    const km = Number((1.2 + (i - 1) * 2.37).toFixed(1));
    const isBarkheraBudniGhat = km >= 54 && km <= 80;
    const isSpecialAlarm = i === 42; // OHE-ET-242 at KM 114.2 (OHE Wire Snap hazard)

    const tension = isSpecialAlarm 
      ? 8.6 
      : isBarkheraBudniGhat 
      ? Number((9.5 + Math.random() * 2.0).toFixed(1)) 
      : Number((11.5 + Math.random() * 1.5).toFixed(1));

    const wear = isSpecialAlarm 
      ? 4.6 
      : isBarkheraBudniGhat 
      ? Number((3.2 + Math.random() * 1.1).toFixed(1)) 
      : Number((1.2 + Math.random() * 1.2).toFixed(1));

    const stagger = Math.floor(-150 + Math.random() * 300);

    let risk = Math.min(100, Math.floor(
      (tension < 10.0 ? (10.0 - tension) * 18 : 0) +
      (wear > 3.5 ? (wear - 3.5) * 25 : 0) +
      (Math.abs(stagger) > 180 ? 20 : 0) +
      (isBarkheraBudniGhat ? 20 : 8)
    ));
    if (isSpecialAlarm) risk = 89;

    const status = risk >= 80 ? "CRITICAL" : risk >= 50 ? "ATTENTION" : "NORMAL";

    assets.push({
      id: `OHE-ET-${idNum}`,
      name: `25kV AC Traction Portal Mast #${idNum} (Cantilever & Contact Wire)`,
      type: "OHE_CATENARY",
      corridorId: "BPL-ET",
      locationKm: `KM ${km.toFixed(1)} (${isBarkheraBudniGhat ? "Ghat Cantilever" : "Standard Mast"})`,
      status,
      failureRisk: risk,
      lastMaintenanceDate: "2026-06-20",
      nextRecommendedInspection: "2026-09-30",
      telemetry: {
        voltage: 25200 + Math.floor(Math.random() * 400 - 200),
        temperature: Number((34 + Math.random() * 12).toFixed(1)),
        oheContactWireTension: tension,
        pantographContactWear: wear,
        catenaryStaggerMm: stagger,
        stressLevel: Math.floor(tension * 15),
        dynamicRiskScore: risk,
      },
      departmentResponsible: "ELEC",
    });
  }

  // C. 30 Signal & Telecom Assets: SIG-JHS-301 to SIG-JHS-330 (KM 0.5 to 119.8)
  for (let i = 1; i <= 30; i++) {
    const idNum = 300 + i;
    const km = Number((0.5 + (i - 1) * 4.05).toFixed(1));
    const isBarkhera = km >= 54 && km <= 60;
    const isSpecialAlert = i === 15; // SIG-JHS-315 at KM 57.2 Barkhera Point Machine

    const switchOpening = isSpecialAlert ? 111.2 : Number((114.5 + Math.random() * 2.0).toFixed(1));
    const voltage = Number((23.6 + Math.random() * 1.2).toFixed(1));
    const frequency = i % 2 === 0 ? "1699Hz" : "2296Hz";

    let risk = Math.min(100, Math.floor(
      (Math.abs(switchOpening - 115) > 2 ? Math.abs(switchOpening - 115) * 15 : 5) +
      (voltage < 23.0 ? 25 : 5) +
      (isBarkhera ? 25 : 5)
    ));
    if (isSpecialAlert) risk = 82;

    const status = risk >= 80 ? "CRITICAL" : risk >= 50 ? "ATTENTION" : "NORMAL";

    assets.push({
      id: `SIG-JHS-${idNum}`,
      name: `Kavach TCAS Beacon & Point Machine Unit #${idNum}`,
      type: i % 3 === 0 ? "POINT_MACHINE" : i % 3 === 1 ? "SIGNAL" : "TRACK_CIRCUIT",
      corridorId: "BPL-ET",
      locationKm: `KM ${km.toFixed(1)} (${km < 30 ? "Bhopal Section" : km < 70 ? "Barkhera Sector" : "Itarsi Approach"})`,
      status,
      failureRisk: risk,
      lastMaintenanceDate: "2026-08-01",
      nextRecommendedInspection: "2026-10-01",
      telemetry: {
        voltage: voltage,
        switchOpeningMm: switchOpening,
        aftcFrequencyHz: frequency,
        cyclesCount: Math.floor(6500 + Math.random() * 5000),
        vibration: Number((0.8 + Math.random() * 1.2).toFixed(2)),
        dynamicRiskScore: risk,
      },
      departmentResponsible: "SNT",
    });
  }

  return assets;
}

export const MOCK_CORRIDOR_ASSETS = generateCorridorAssets();

// ==========================================
// 3. 15 LIVE TRAINS (BHOPAL - ITARSI CORRIDOR)
// ==========================================
export const MOCK_LIVE_TRAINS: LiveTrain[] = [
  {
    id: "TRN-12002",
    trainNumber: "12002",
    trainName: "New Delhi - Rani Kamlapati Shatabdi Express",
    priority: 1,
    trainType: "PREMIUM_SUPERFAST",
    currentKm: 18.4,
    currentSpeedKmph: 110,
    maxSpeedKmph: 130,
    direction: "DOWN",
    trackLine: "DOWN_LINE",
    nextBlockSection: "Mandideep (MDDP)",
    delayMinutes: 0,
    origin: "NDLS",
    destination: "RKMP",
    locoNumber: "WAP-7 #30482 (GZB Shed)",
    status: "RUNNING_ON_TIME",
  },
  {
    id: "TRN-22470",
    trainNumber: "22470",
    trainName: "Vande Bharat Express (Rani Kamlapati - Hazrat Nizamuddin)",
    priority: 1,
    trainType: "PREMIUM_SUPERFAST",
    currentKm: 42.1,
    currentSpeedKmph: 125,
    maxSpeedKmph: 130,
    direction: "UP",
    trackLine: "UP_LINE",
    nextBlockSection: "Obaidullaganj (ODG)",
    delayMinutes: 0,
    origin: "RKMP",
    destination: "NZM",
    locoNumber: "TrainSet-18 Vande Bharat Rake #08",
    status: "RUNNING_ON_TIME",
  },
  {
    id: "TRN-12156",
    trainNumber: "12156",
    trainName: "Shaan-e-Bhopal Superfast Express",
    priority: 2,
    trainType: "PREMIUM_SUPERFAST",
    currentKm: 65.2,
    currentSpeedKmph: 92,
    maxSpeedKmph: 120,
    direction: "DOWN",
    trackLine: "DOWN_LINE",
    nextBlockSection: "Budni (BNI Mid-Ghat)",
    delayMinutes: 8,
    origin: "NZM",
    destination: "RKMP",
    locoNumber: "WAP-7 #39104 (TKD Shed)",
    status: "DELAYED",
  },
  {
    id: "TRN-12616",
    trainNumber: "12616",
    trainName: "Grand Trunk (GT) Express",
    priority: 2,
    trainType: "EXPRESS",
    currentKm: 84.5,
    currentSpeedKmph: 78,
    maxSpeedKmph: 110,
    direction: "DOWN",
    trackLine: "DOWN_LINE",
    nextBlockSection: "Narmadapuram (NDPM)",
    delayMinutes: 14,
    origin: "NDLS",
    destination: "MAS",
    locoNumber: "WAP-7 #30219 (RPM Shed)",
    status: "DELAYED",
  },
  {
    id: "TRN-12622",
    trainNumber: "12622",
    trainName: "Tamil Nadu Superfast Express",
    priority: 2,
    trainType: "EXPRESS",
    currentKm: 102.3,
    currentSpeedKmph: 88,
    maxSpeedKmph: 120,
    direction: "DOWN",
    trackLine: "DOWN_LINE",
    nextBlockSection: "Itarsi Junction (ET Outer)",
    delayMinutes: 0,
    origin: "NDLS",
    destination: "MAS",
    locoNumber: "WAP-7 #37210 (LGD Shed)",
    status: "RUNNING_ON_TIME",
  },
  {
    id: "TRN-12724",
    trainNumber: "12724",
    trainName: "Telangana Superfast Express",
    priority: 2,
    trainType: "EXPRESS",
    currentKm: 31.8,
    currentSpeedKmph: 95,
    maxSpeedKmph: 120,
    direction: "UP",
    trackLine: "UP_LINE",
    nextBlockSection: "Mandideep (MDDP)",
    delayMinutes: 0,
    origin: "HYB",
    destination: "NDLS",
    locoNumber: "WAP-7 #30315 (KZJ Shed)",
    status: "RUNNING_ON_TIME",
  },
  {
    id: "TRN-12920",
    trainNumber: "12920",
    trainName: "Malwa Superfast Express",
    priority: 3,
    trainType: "EXPRESS",
    currentKm: 51.0,
    currentSpeedKmph: 72,
    maxSpeedKmph: 110,
    direction: "UP",
    trackLine: "UP_LINE",
    nextBlockSection: "Barkhera (BKA)",
    delayMinutes: 22,
    origin: "SVDK",
    destination: "DADN",
    locoNumber: "WAP-5 #30022 (BRC Shed)",
    status: "DELAYED",
  },
  {
    id: "TRN-18238",
    trainNumber: "18238",
    trainName: "Chhattisgarh Express",
    priority: 3,
    trainType: "EXPRESS",
    currentKm: 72.4,
    currentSpeedKmph: 65,
    maxSpeedKmph: 105,
    direction: "DOWN",
    trackLine: "DOWN_LINE",
    nextBlockSection: "Budni (BNI)",
    delayMinutes: 18,
    origin: "ASR",
    destination: "BSP",
    locoNumber: "WAP-7 #30511 (BIA Shed)",
    status: "DELAYED",
  },
  {
    id: "TRN-11078",
    trainNumber: "11078",
    trainName: "Jhelum Express",
    priority: 3,
    trainType: "EXPRESS",
    currentKm: 111.0,
    currentSpeedKmph: 80,
    maxSpeedKmph: 110,
    direction: "DOWN",
    trackLine: "DOWN_LINE",
    nextBlockSection: "Itarsi Yard",
    delayMinutes: 5,
    origin: "JAT",
    destination: "PUNE",
    locoNumber: "WAP-7 #30412 (ET Shed)",
    status: "RUNNING_ON_TIME",
  },
  {
    id: "TRN-12138",
    trainNumber: "12138",
    trainName: "Punjab Mail",
    priority: 3,
    trainType: "EXPRESS",
    currentKm: 14.2,
    currentSpeedKmph: 85,
    maxSpeedKmph: 110,
    direction: "UP",
    trackLine: "UP_LINE",
    nextBlockSection: "Rani Kamlapati (RKMP)",
    delayMinutes: 0,
    origin: "FZR",
    destination: "CSMT",
    locoNumber: "WAP-7 #30650 (AQ Shed)",
    status: "RUNNING_ON_TIME",
  },
  {
    id: "TRN-01666",
    trainNumber: "01666",
    trainName: "Bhopal - Itarsi MEMU Commuter Special",
    priority: 4,
    trainType: "EXPRESS",
    currentKm: 37.6,
    currentSpeedKmph: 52,
    maxSpeedKmph: 80,
    direction: "DOWN",
    trackLine: "DOWN_LINE",
    nextBlockSection: "Obaidullaganj (ODG)",
    delayMinutes: 0,
    origin: "BPL",
    destination: "ET",
    locoNumber: "3-Phase AC MEMU Rake",
    status: "RUNNING_ON_TIME",
  },
  {
    id: "TRN-FRT-COAL",
    trainNumber: "BCN-E/Sarni",
    trainName: "Heavy Freight Rake (Thermal Coal to Sarni Power)",
    priority: 4,
    trainType: "FREIGHT_HEAVY",
    currentKm: 58.2,
    currentSpeedKmph: 0,
    maxSpeedKmph: 75,
    direction: "DOWN",
    trackLine: "LOOP_LINE",
    nextBlockSection: "Barkhera Loop 2 (Regulated for Express Priority)",
    delayMinutes: 35,
    origin: "DDU",
    destination: "SARNI",
    locoNumber: "Twin WAG-9HC #32810 + #32811 (ET Shed)",
    status: "HALTED_AT_SIGNAL",
  },
  {
    id: "TRN-FRT-IRON",
    trainNumber: "BOXN/Bhilai",
    trainName: "BOXN Heavy-Haul Iron Rake (Bhilai to Mandideep)",
    priority: 4,
    trainType: "FREIGHT_HEAVY",
    currentKm: 89.2,
    currentSpeedKmph: 48,
    maxSpeedKmph: 75,
    direction: "UP",
    trackLine: "UP_LINE",
    nextBlockSection: "Budni Ghat Entry",
    delayMinutes: 0,
    origin: "BIA",
    destination: "MDDP",
    locoNumber: "WAG-12B Electric (#60048 Alstom Madhepura)",
    status: "RUNNING_ON_TIME",
  },
  {
    id: "TRN-FRT-POL",
    trainNumber: "BTPN/Petro",
    trainName: "BTPN Petroleum Tanker Rake (IOCL Refinery)",
    priority: 4,
    trainType: "FREIGHT_CONTAINER",
    currentKm: 108.5,
    currentSpeedKmph: 42,
    maxSpeedKmph: 75,
    direction: "UP",
    trackLine: "UP_LINE",
    nextBlockSection: "Narmadapuram Up Block",
    delayMinutes: 0,
    origin: "BPCL/MUM",
    destination: "BPL",
    locoNumber: "WAG-9H #31720 (TKD Shed)",
    status: "RUNNING_ON_TIME",
  },
  {
    id: "TRN-WRK-TAMP",
    trainNumber: "TAMP-SP-04",
    trainName: "Plasser Quick Relaying & Track Tamping Work Train",
    priority: 5,
    trainType: "WORK_SPECIAL",
    currentKm: 56.1,
    currentSpeedKmph: 22,
    maxSpeedKmph: 40,
    direction: "DOWN",
    trackLine: "DOWN_LINE",
    nextBlockSection: "Barkhera Ghat Work Zone (Sanction Pending)",
    delayMinutes: 0,
    origin: "BPL Depot",
    destination: "KM 56.4 Work Site",
    locoNumber: "Self-Propelled Plasser 09-3X Machine",
    status: "SLOWED_CAUTION",
    cautionOrderApplied: "Caution 30 km/h under G&SR 15.06",
  },
];

// ==========================================
// 4. 25+ MAINTENANCE BLOCK REQUESTS
// Ready for AI Bundling & Approval
// ==========================================
export const MOCK_BLOCK_REQUESTS: MaintenanceBlockRequest[] = [
  // --- PRIMARY BUNDLE CANDIDATE 1 (Barkhera Ghat Section KM 55.0 to 58.5) ---
  {
    id: "REQ-BPL-CV-101",
    blockId: "BLK-BPL-CV-101",
    title: "Track Deep Screening & Dynamic Tamping Machine Deployment",
    department: "Civil",
    departmentId: "ENG",
    corridorId: "BPL-ET",
    fromKm: 55.0,
    toKm: 58.0,
    locationSection: "Barkhera (KM 56) Ghat Curve 14",
    trackLine: "DOWN_LINE",
    requestedWindow: "04:30 - 06:30 IST",
    durationHours: 2.0,
    scheduledDate: "Tomorrow",
    resourceRequirements: ["Plasser 09-3X Tamping Machine", "Ballast Regulator BRM", "P-Way Gang 14"],
    cautionSpeedRequiredKmph: 30,
    requiresOHEPowerCut: false,
    status: "Submitted",
    riskScore: 88,
    description: "Ballast fouled up to 65% on curve 14; gauge deviation +6.8mm requires immediate tamping to prevent speed restrictions.",
    requestedBy: "Sunil Deshmukh (Sr. Section Engineer P-Way)",
  },
  {
    id: "REQ-BPL-EL-201",
    blockId: "BLK-BPL-EL-201",
    title: "25kV Catenary Wire Dropper Replacement & Insulator Washing",
    department: "Electrical/OHE",
    departmentId: "ELEC",
    corridorId: "BPL-ET",
    fromKm: 55.2,
    toKm: 57.8,
    locationSection: "Barkhera (KM 56) Portals OHE-224 to 226",
    trackLine: "DOWN_LINE",
    requestedWindow: "05:00 - 07:00 IST",
    durationHours: 2.0,
    scheduledDate: "Tomorrow",
    resourceRequirements: ["OHE 8-Wheeler Tower Wagon #104", "Earthing Discharge Rods (2 pairs)", "Traction Linemen Team"],
    cautionSpeedRequiredKmph: 45,
    requiresOHEPowerCut: true,
    status: "Submitted",
    riskScore: 82,
    description: "Catenary wire tension dropped to 8.9 kN at portal 225. Requires 25kV power cutoff and dropper renewal.",
    requestedBy: "K. Ramanathan (Sr. DEE Traction)",
  },
  {
    id: "REQ-BPL-ST-301",
    blockId: "BLK-BPL-ST-301",
    title: "Kavach RFID Trackside Beacon Calibration & Signal Cable Trenching",
    department: "Signal & Traffic",
    departmentId: "SNT",
    corridorId: "BPL-ET",
    fromKm: 56.0,
    toKm: 58.5,
    locationSection: "Barkhera Down Approach Signals",
    trackLine: "DOWN_LINE",
    requestedWindow: "04:45 - 07:15 IST",
    durationHours: 2.5,
    scheduledDate: "Tomorrow",
    resourceRequirements: ["S&T Calibration Trolley", "Kavach Diagnostic Toolset", "Signal Inspector Crew"],
    cautionSpeedRequiredKmph: 30,
    requiresOHEPowerCut: false,
    status: "Submitted",
    riskScore: 76,
    description: "Signal S-24 repeater cable damaged by rodent chewing; track circuit TC-56 intermittent voltage dips.",
    requestedBy: "Ananya Sharma (Sr. Section Engineer Kavach)",
  },

  // --- SECONDARY BUNDLE CANDIDATE 2 (Mandideep Industrial Sector KM 22.0 to 26.0) ---
  {
    id: "REQ-BPL-CV-102",
    blockId: "BLK-BPL-CV-102",
    title: "Turnout 101B Thick Web Switch Rail Tongue Replacement",
    department: "Civil",
    departmentId: "ENG",
    corridorId: "BPL-ET",
    fromKm: 23.5,
    toKm: 25.5,
    locationSection: "Mandideep Yard (KM 24)",
    trackLine: "UP_LINE",
    requestedWindow: "01:00 - 03:30 IST",
    durationHours: 2.5,
    scheduledDate: "Tomorrow",
    resourceRequirements: ["Crane 140T Special", "Rail Welding Flash-Butt Plant", "P-Way Heavy Gang"],
    cautionSpeedRequiredKmph: 20,
    requiresOHEPowerCut: true,
    status: "Submitted",
    riskScore: 74,
    description: "Tongue rail wear at 4.2mm exceeding 3.5mm limit; switch angle point machine junction refurbishment.",
    requestedBy: "Sunil Deshmukh (Sr. Section Engineer P-Way)",
  },
  {
    id: "REQ-BPL-EL-202",
    blockId: "BLK-BPL-EL-202",
    title: "Section Insulator Overhaul & Neutral Section Inspection",
    department: "Electrical/OHE",
    departmentId: "ELEC",
    corridorId: "BPL-ET",
    fromKm: 23.0,
    toKm: 25.0,
    locationSection: "Mandideep Up Line Neutral Zone",
    trackLine: "UP_LINE",
    requestedWindow: "01:30 - 03:30 IST",
    durationHours: 2.0,
    scheduledDate: "Tomorrow",
    resourceRequirements: ["Tower Wagon #102", "Section Insulator Spares", "TPC Grounding Kit"],
    cautionSpeedRequiredKmph: 30,
    requiresOHEPowerCut: true,
    status: "Submitted",
    riskScore: 68,
    description: "Neutral section PTFE runners showing flashover burn marks; needs cleaning and contact wire alignment.",
    requestedBy: "K. Ramanathan (Sr. DEE Traction)",
  },
  {
    id: "REQ-BPL-ST-302",
    blockId: "BLK-BPL-ST-302",
    title: "Axle Counter Dual Sensor Resynchronization & Point Motor Testing",
    department: "Signal & Traffic",
    departmentId: "SNT",
    corridorId: "BPL-ET",
    fromKm: 24.0,
    toKm: 26.2,
    locationSection: "Mandideep North Cabin",
    trackLine: "UP_LINE",
    requestedWindow: "01:15 - 03:45 IST",
    durationHours: 2.5,
    scheduledDate: "Tomorrow",
    resourceRequirements: ["DAC High Frequency Analyzer", "S&T Shift Engineers"],
    cautionSpeedRequiredKmph: 30,
    requiresOHEPowerCut: false,
    status: "Submitted",
    riskScore: 71,
    description: "Digital Axle Counter wheel sensor pulse jitter detected during peak rake cross-overs.",
    requestedBy: "Ananya Sharma (Sr. Section Engineer Kavach)",
  },

  // --- THIRD BUNDLE CANDIDATE 3 (Budni - Narmada Approach KM 76.0 to 80.0) ---
  {
    id: "REQ-BPL-CV-103",
    blockId: "BLK-BPL-CV-103",
    title: "USFD Ultrasonic Flaw Detection Rail Weld Testing",
    department: "Civil",
    departmentId: "ENG",
    corridorId: "BPL-ET",
    fromKm: 76.0,
    toKm: 79.5,
    locationSection: "Budni (KM 78) Narmada River Approach",
    trackLine: "BOTH_LINES",
    requestedWindow: "10:00 - 12:30 IST",
    durationHours: 2.5,
    scheduledDate: "2026-09-25",
    resourceRequirements: ["Digital USFD Double Rail Tester", "P-Way Flaw Marking Crew"],
    cautionSpeedRequiredKmph: 50,
    requiresOHEPowerCut: false,
    status: "Draft",
    riskScore: 64,
    description: "Mandatory periodic USFD scanning of thermit welds across high-stress bridge approaches under IRPWM Para 804.",
    requestedBy: "Vikram Singh (Chief Track Engineer)",
  },
  {
    id: "REQ-BPL-EL-203",
    blockId: "BLK-BPL-EL-203",
    title: "OHE Feeder Wire Bracket Replacement on Narmada Viaduct",
    department: "Electrical/OHE",
    departmentId: "ELEC",
    corridorId: "BPL-ET",
    fromKm: 77.0,
    toKm: 79.0,
    locationSection: "Budni Mid-Viaduct Piers 12 to 24",
    trackLine: "BOTH_LINES",
    requestedWindow: "10:15 - 12:45 IST",
    durationHours: 2.5,
    scheduledDate: "2026-09-25",
    resourceRequirements: ["Bridge Inspection Cradle", "Traction Crew"],
    cautionSpeedRequiredKmph: 40,
    requiresOHEPowerCut: true,
    status: "Draft",
    riskScore: 59,
    description: "Rusting bracket clamps on viaduct bridge pier OHE supports require zinc galvanizing replacement.",
    requestedBy: "K. Ramanathan (Sr. DEE Traction)",
  },

  // --- MORE INDIVIDUAL & ACTIVE REQUESTS ACROSS CORRIDOR ---
  {
    id: "REQ-BPL-SF-401",
    blockId: "BLK-BPL-SF-401",
    title: "Statutory CRS Safety Clearance & High-Speed Oscillation Audit",
    department: "Safety",
    departmentId: "SFTY",
    corridorId: "BPL-ET",
    fromKm: 50.0,
    toKm: 65.0,
    locationSection: "Barkhera - Budni Ghat Section",
    trackLine: "BOTH_LINES",
    requestedWindow: "03:00 - 05:00 IST",
    durationHours: 2.0,
    scheduledDate: "2026-09-26",
    resourceRequirements: ["Oscillograph Car OMS-2000", "Safety Directorate Officers"],
    cautionSpeedRequiredKmph: 60,
    requiresOHEPowerCut: false,
    status: "Submitted",
    riskScore: 80,
    description: "CRS mandate: Comprehensive ride index audit before clearing Vande Bharat 130 km/h speed certificate.",
    requestedBy: "Devendra Yadav (Chief Safety Officer)",
  },
  {
    id: "REQ-BPL-CV-104",
    blockId: "BLK-BPL-CV-104",
    title: "Bridge #148 Bearing Plate Lubrication & Rock Anchor Torquing",
    department: "Civil",
    departmentId: "ENG",
    corridorId: "BPL-ET",
    fromKm: 95.0,
    toKm: 97.2,
    locationSection: "Narmadapuram Bridge Approach",
    trackLine: "DOWN_LINE",
    requestedWindow: "14:00 - 16:30 IST",
    durationHours: 2.5,
    scheduledDate: "2026-09-27",
    resourceRequirements: ["Hydraulic Jacks 200T", "Bridge Inspection Car"],
    cautionSpeedRequiredKmph: 20,
    requiresOHEPowerCut: false,
    status: "Draft",
    riskScore: 62,
    description: "Elastomeric bearing pads showing 8mm displacement under monsoon thermal cycle.",
  },
  {
    id: "REQ-BPL-EL-204",
    blockId: "BLK-BPL-EL-204",
    title: "Traction Substation TSS-02 Transformer Oil Centrifuging",
    department: "Electrical/OHE",
    departmentId: "ELEC",
    corridorId: "BPL-ET",
    fromKm: 37.0,
    toKm: 39.0,
    locationSection: "Obaidullaganj Substation",
    trackLine: "UP_LINE",
    requestedWindow: "02:00 - 05:00 IST",
    durationHours: 3.0,
    scheduledDate: "2026-09-28",
    resourceRequirements: ["Mobile Oil Filtration Plant", "TSS Crew"],
    cautionSpeedRequiredKmph: 50,
    requiresOHEPowerCut: true,
    status: "Draft",
    riskScore: 48,
    description: "Transformer BDV dropped to 48kV; needs oil vacuum drying and dissolved gas analysis (DGA).",
  },
  {
    id: "REQ-BPL-ST-303",
    blockId: "BLK-BPL-ST-303",
    title: "Electronic Interlocking EI VDU Standby Channel Diagnostic",
    department: "Signal & Traffic",
    departmentId: "SNT",
    corridorId: "BPL-ET",
    fromKm: 118.0,
    toKm: 120.0,
    locationSection: "Itarsi North Interlocking Tower",
    trackLine: "BOTH_LINES",
    requestedWindow: "03:30 - 05:00 IST",
    durationHours: 1.5,
    scheduledDate: "Tomorrow",
    resourceRequirements: ["Ansaldo OEM Systems Engineer", "S&T Supervisors"],
    cautionSpeedRequiredKmph: 30,
    requiresOHEPowerCut: false,
    status: "Submitted",
    riskScore: 72,
    description: "Redundant Channel B communication watchdog timer timeout observed during heavy lightning.",
  },
  {
    id: "REQ-BPL-CV-105",
    blockId: "BLK-BPL-CV-105",
    title: "Track Formation Geotextile Layer Injection for Soil Stabilization",
    department: "Civil",
    departmentId: "ENG",
    corridorId: "BPL-ET",
    fromKm: 7.0,
    toKm: 9.5,
    locationSection: "Rani Kamlapati South Curve",
    trackLine: "DOWN_LINE",
    requestedWindow: "00:30 - 03:00 IST",
    durationHours: 2.5,
    scheduledDate: "2026-09-29",
    resourceRequirements: ["Soil Grouting Rig", "Geogrid Spares", "P-Way Batch"],
    cautionSpeedRequiredKmph: 45,
    requiresOHEPowerCut: false,
    status: "Draft",
    riskScore: 53,
    description: "Cess erosion and clay pumping in ballast shoulder after heavy monsoon precipitation.",
  },
  {
    id: "REQ-BPL-EL-205",
    blockId: "BLK-BPL-EL-205",
    title: "Auto-Tensioning Device (ATD) Counterweight Pulley Greasing",
    department: "Electrical/OHE",
    departmentId: "ELEC",
    corridorId: "BPL-ET",
    fromKm: 82.0,
    toKm: 85.0,
    locationSection: "Budni - Narmadapuram Section",
    trackLine: "UP_LINE",
    requestedWindow: "09:00 - 11:00 IST",
    durationHours: 2.0,
    scheduledDate: "2026-09-29",
    resourceRequirements: ["Ladder Trolley", "OHE Linemen"],
    cautionSpeedRequiredKmph: 60,
    requiresOHEPowerCut: true,
    status: "Draft",
    riskScore: 41,
    description: "Counterweight stainless steel wire ropes require grease pack and tension check at 35°C ambient.",
  },
  {
    id: "REQ-BPL-ST-304",
    blockId: "BLK-BPL-ST-304",
    title: "Optical Fiber Cable (OFC) Armoured Joint Box Splice Protection",
    department: "Signal & Traffic",
    departmentId: "SNT",
    corridorId: "BPL-ET",
    fromKm: 44.0,
    toKm: 46.0,
    locationSection: "Obaidullaganj South KM 45",
    trackLine: "BOTH_LINES",
    requestedWindow: "11:00 - 13:00 IST",
    durationHours: 2.0,
    scheduledDate: "2026-09-30",
    resourceRequirements: ["OTDR Fiber Splicer", "Telecom Gang"],
    cautionSpeedRequiredKmph: 75,
    requiresOHEPowerCut: false,
    status: "Draft",
    riskScore: 35,
    description: "OFC loss increased to 0.45 dB/km on fiber pair 7-8; water ingress suspected in joint pit.",
  },
  {
    id: "REQ-BPL-SF-402",
    blockId: "BLK-BPL-SF-402",
    title: "Emergency Derailment Mock Drill & Breakaway Siding Inspection",
    department: "Safety",
    departmentId: "SFTY",
    corridorId: "BPL-ET",
    fromKm: 54.0,
    toKm: 56.0,
    locationSection: "Barkhera Catch Siding 1",
    trackLine: "UP_LINE",
    requestedWindow: "02:00 - 04:30 IST",
    durationHours: 2.5,
    scheduledDate: "2026-10-02",
    resourceRequirements: ["ART Breakdown Crane", "Medical Relief Van", "Disaster Response Force"],
    cautionSpeedRequiredKmph: 15,
    requiresOHEPowerCut: true,
    status: "Draft",
    riskScore: 70,
    description: "Annual statutory simulation of runaway train catch siding trap switch activation in ghat section.",
  },
  {
    id: "REQ-BPL-CV-106",
    blockId: "BLK-BPL-CV-106",
    title: "Culvert #42 De-silting & Headwall Concrete Grouting",
    department: "Civil",
    departmentId: "ENG",
    corridorId: "BPL-ET",
    fromKm: 32.0,
    toKm: 33.5,
    locationSection: "Mandideep - Obaidullaganj",
    trackLine: "BOTH_LINES",
    requestedWindow: "13:00 - 15:30 IST",
    durationHours: 2.5,
    scheduledDate: "2026-10-03",
    resourceRequirements: ["Excavator Backhoe", "Masonry Team"],
    cautionSpeedRequiredKmph: 45,
    requiresOHEPowerCut: false,
    status: "Draft",
    riskScore: 39,
    description: "Culvert waterway choked with industrial silt; potential water logging during cloudburst.",
  },
  {
    id: "REQ-BPL-EL-206",
    blockId: "BLK-BPL-EL-206",
    title: "OHE Jumper Wire Thermal Imaging & Hot Spot Remediation",
    department: "Electrical/OHE",
    departmentId: "ELEC",
    corridorId: "BPL-ET",
    fromKm: 110.0,
    toKm: 115.0,
    locationSection: "Itarsi Outer Portals 240-245",
    trackLine: "DOWN_LINE",
    requestedWindow: "04:00 - 06:00 IST",
    durationHours: 2.0,
    scheduledDate: "2026-09-24",
    resourceRequirements: ["Tower Wagon #106", "FLIR Thermal Camera", "PG Clamps"],
    cautionSpeedRequiredKmph: 30,
    requiresOHEPowerCut: true,
    status: "Sanctioned",
    riskScore: 84,
    description: "Thermal imaging revealed PG clamp temperature 78°C (delta 42°C over ambient); imminent burnout.",
    t806Id: "SANCTION-T806-089",
  },
  {
    id: "REQ-BPL-ST-305",
    blockId: "BLK-BPL-ST-305",
    title: "Track Circuit AFTC Receiver Tuning & Tuning Unit Replacement",
    department: "Signal & Traffic",
    departmentId: "SNT",
    corridorId: "BPL-ET",
    fromKm: 112.0,
    toKm: 114.5,
    locationSection: "Itarsi Down Home Approach",
    trackLine: "DOWN_LINE",
    requestedWindow: "04:30 - 06:00 IST",
    durationHours: 1.5,
    scheduledDate: "2026-09-24",
    resourceRequirements: ["Audio Frequency Meter", "S&T Technicians"],
    cautionSpeedRequiredKmph: 30,
    requiresOHEPowerCut: false,
    status: "Bundled",
    bundleId: "MB-BPL-2026-02",
    riskScore: 77,
    description: "Tuning unit impedance drift causing erratic block clear signals during heavy rain.",
  },
  {
    id: "REQ-BPL-CV-107",
    blockId: "BLK-BPL-CV-107",
    title: "Rail End Batter Grinding & Joint Stagger Alignment",
    department: "Civil",
    departmentId: "ENG",
    corridorId: "BPL-ET",
    fromKm: 111.5,
    toKm: 114.0,
    locationSection: "Itarsi Down Goods Line",
    trackLine: "DOWN_LINE",
    requestedWindow: "04:15 - 06:15 IST",
    durationHours: 2.0,
    scheduledDate: "2026-09-24",
    resourceRequirements: ["Profile Grinding Machine", "Track Welders"],
    cautionSpeedRequiredKmph: 30,
    requiresOHEPowerCut: false,
    status: "Bundled",
    bundleId: "MB-BPL-2026-02",
    riskScore: 81,
    description: "Fishplated insulated joints battered up to 3.2mm; grinding required to prevent rail fracture.",
  },
  {
    id: "REQ-BPL-CV-108",
    blockId: "BLK-BPL-CV-108",
    title: "Deep Screening of Ballast on Up Line Curve 8",
    department: "Civil",
    departmentId: "ENG",
    corridorId: "BPL-ET",
    fromKm: 60.0,
    toKm: 62.5,
    locationSection: "Barkhera South Up Line",
    trackLine: "UP_LINE",
    requestedWindow: "05:00 - 07:30 IST",
    durationHours: 2.5,
    scheduledDate: "2026-09-23",
    resourceRequirements: ["BCM Ballast Cleaner", "Hopper Rake"],
    cautionSpeedRequiredKmph: 30,
    requiresOHEPowerCut: false,
    status: "Active",
    riskScore: 75,
    description: "Currently in progress under T/806 block authority. Ballast cushion replenishment.",
    t806Id: "SANCTION-T806-088",
  },
  {
    id: "REQ-BPL-EL-207",
    blockId: "BLK-BPL-EL-207",
    title: "Emergency Isolator Overhaul at Feeding Post FP-01",
    department: "Electrical/OHE",
    departmentId: "ELEC",
    corridorId: "BPL-ET",
    fromKm: 59.5,
    toKm: 61.5,
    locationSection: "Barkhera FP-01",
    trackLine: "UP_LINE",
    requestedWindow: "05:15 - 07:15 IST",
    durationHours: 2.0,
    scheduledDate: "2026-09-23",
    resourceRequirements: ["Isolator Overhaul Kit", "TPC Grounding Crew"],
    cautionSpeedRequiredKmph: 30,
    requiresOHEPowerCut: true,
    status: "Active",
    riskScore: 79,
    description: "Currently active: 25kV power cutoff permit #PTW-2026-094 issued by Bhopal TPC.",
    t806Id: "SANCTION-T806-088",
  },
  {
    id: "REQ-BPL-CV-109",
    blockId: "BLK-BPL-CV-109",
    title: "Emergency Rail Fracture Clamping at KM 114/2",
    department: "Civil",
    departmentId: "ENG",
    corridorId: "BPL-ET",
    fromKm: 113.8,
    toKm: 114.6,
    locationSection: "Budni - Narmadapuram Down Line",
    trackLine: "DOWN_LINE",
    requestedWindow: "15:00 - 17:00 IST",
    durationHours: 2.0,
    scheduledDate: "2026-09-22",
    resourceRequirements: ["Emergency Jogged Fishplate Kit", "P-Way Rapid Response"],
    cautionSpeedRequiredKmph: 20,
    requiresOHEPowerCut: false,
    status: "Closed",
    riskScore: 95,
    description: "Hairline fracture repaired with jogged fishplates and clamp; final thermit welding completed and line clear certified.",
  },
  {
    id: "REQ-BPL-EL-208",
    blockId: "BLK-BPL-EL-208",
    title: "Emergency Pantograph Entanglement Clearing at KM 38/6",
    department: "Electrical/OHE",
    departmentId: "ELEC",
    corridorId: "BPL-ET",
    fromKm: 38.0,
    toKm: 39.2,
    locationSection: "Obaidullaganj Down Main",
    trackLine: "DOWN_LINE",
    requestedWindow: "08:00 - 10:30 IST",
    durationHours: 2.5,
    scheduledDate: "2026-09-21",
    resourceRequirements: ["Tower Wagon #101", "Traction Linesmen"],
    cautionSpeedRequiredKmph: 45,
    requiresOHEPowerCut: true,
    status: "Closed",
    riskScore: 91,
    description: "Freight train pantograph entangled with dropper wire; section cleared, wire spliced and re-energized successfully.",
  },
  {
    id: "REQ-BPL-ST-306",
    blockId: "BLK-BPL-ST-306",
    title: "Lightning Surge Suppressor Replacement at Mandideep Relay Room",
    department: "Signal & Traffic",
    departmentId: "SNT",
    corridorId: "BPL-ET",
    fromKm: 23.8,
    toKm: 24.5,
    locationSection: "Mandideep Station Relay Room",
    trackLine: "BOTH_LINES",
    requestedWindow: "14:00 - 15:30 IST",
    durationHours: 1.5,
    scheduledDate: "2026-09-20",
    resourceRequirements: ["Class B & C Surge Protectors", "S&T Inspector"],
    cautionSpeedRequiredKmph: 60,
    requiresOHEPowerCut: false,
    status: "Closed",
    riskScore: 65,
    description: "Surge arrestors blown after thunderstorm; replaced and insulation resistance tested at 500V Megger.",
  },
  {
    id: "REQ-BPL-CV-110",
    blockId: "BLK-BPL-CV-110",
    title: "Track Tamping from KM 2.0 to KM 5.5",
    department: "Civil",
    departmentId: "ENG",
    corridorId: "BPL-ET",
    fromKm: 2.0,
    toKm: 5.5,
    locationSection: "Bhopal - Rani Kamlapati Sub-urban",
    trackLine: "UP_LINE",
    requestedWindow: "01:00 - 03:00 IST",
    durationHours: 2.0,
    scheduledDate: "2026-09-19",
    resourceRequirements: ["Plasser CSM Tamping Machine"],
    cautionSpeedRequiredKmph: 40,
    requiresOHEPowerCut: false,
    status: "Closed",
    riskScore: 55,
    description: "Routine maintenance tamping; 3.5 track kilometers compacted to standard ballast profile.",
  }
];

// ==========================================
// 5. STATUTORY T/806 SANCTIONS (G&SR 1976)
// ==========================================
export const MOCK_T806_SANCTIONS: StatutoryT806Sanction[] = [
  {
    id: "SANCTION-T806-088",
    sanctionNumber: "WCR/BPL-ET/T806/2026/088",
    blockId: "MB-BPL-2026-01",
    corridorId: "BPL-ET",
    corridorName: "Bhopal - Itarsi High-Density Trunk Corridor",
    fromKm: 59.5,
    toKm: 62.5,
    trackLine: "UP_LINE",
    sanctionedWindow: "05:00 - 07:30 IST",
    durationHours: 2.5,
    cautionSpeedKmph: 30,
    tractionPowerCutoff: true,
    ohePermitToWorkNumber: "PTW-WCR-BPL-2026-094",
    tpcIsolationCertificateNumber: "TIC-BPL-TSS01-449",
    associatedBundleId: "MB-BPL-2026-01",
    gsrRulesCited: [
      "G&SR 15.06 (Imposition of Line Block on Running Track)",
      "G&SR 17.08 (Electric Traction Working & 25kV Isolation)",
      "IRPWM 2020 Para 804 (Deep Screening Safety Clearance)",
      "IRACTM Vol II Para 203 (Permit to Work Protocol)"
    ],
    signoffPipeline: {
      step1DeptSubmission: {
        completed: true,
        by: "Sunil Deshmukh (Sr. SE P-Way) & K. Ramanathan (Sr. DEE)",
        timestamp: "2026-09-22 17:30:15 IST",
      },
      step2PowerIsolation: {
        completed: true,
        by: "S. K. Gupta (Traction Power Controller - Bhopal)",
        certificate: "TIC-BPL-TSS01-449 / Earthing Verified at Mast 230 & 236",
        timestamp: "2026-09-23 04:45:10 IST",
      },
      step3TrafficSanction: {
        completed: true,
        by: "Rajesh Verma (Executive Director - Railway Board)",
        timestamp: "2026-09-23 04:55:00 IST",
      },
      step4T806Issued: {
        completed: true,
        by: "Devendra Yadav (Chief Safety Officer - CRS Compliance)",
        timestamp: "2026-09-23 05:00:00 IST",
        qrCodeHash: "sha256:9f8e4b2d1a3c7e5f0a2b4c6e8d0f1a3b5c7e9a1b3d5f7a9c1e3b5d7f9a1b3d5f",
      }
    },
    currentStep: 4,
    status: "ACTIVE_BLOCK",
    issuingOfficer: "Rajesh Verma / Devendra Yadav",
    issuingDesignation: "Executive Director (Railway Board) & Chief Safety Officer",
    participatingDepartments: ["Civil (P-Way)", "Electrical (OHE)", "Safety Directorate"],
    digitalSignatureHash: "e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855",
    previousHash: "a1b2c3d4e5f60718293a4b5c6d7e8f90123456789abcdef0123456789abcdef0",
    issuedAt: "23 Sep 2026, 05:00:00 IST",
    cautionOrderSummary: "TSR 30 km/h on Up Line between KM 59.5 and KM 62.5; Neutral Section energization locked out."
  },
  {
    id: "SANCTION-T806-089",
    sanctionNumber: "WCR/BPL-ET/T806/2026/089",
    blockId: "BLK-BPL-EL-206",
    corridorId: "BPL-ET",
    corridorName: "Bhopal - Itarsi High-Density Trunk Corridor",
    fromKm: 110.0,
    toKm: 115.0,
    trackLine: "DOWN_LINE",
    sanctionedWindow: "04:00 - 06:00 IST",
    durationHours: 2.0,
    cautionSpeedKmph: 30,
    tractionPowerCutoff: true,
    ohePermitToWorkNumber: "PTW-WCR-ET-2026-102",
    tpcIsolationCertificateNumber: "TIC-ET-TSS03-512",
    associatedRequestId: "REQ-BPL-EL-206",
    gsrRulesCited: [
      "G&SR 15.06 (Imposition of Line Block)",
      "G&SR 17.08 (Power Cutoff Verification)",
      "IRACTM Vol II Para 208 (Hotspot Remediation)"
    ],
    signoffPipeline: {
      step1DeptSubmission: {
        completed: true,
        by: "K. Ramanathan (Sr. DEE Traction)",
        timestamp: "2026-09-23 08:15:00 IST",
      },
      step2PowerIsolation: {
        completed: true,
        by: "M. P. Sharma (TPC Itarsi)",
        certificate: "TIC-ET-TSS03-512",
        timestamp: "2026-09-23 08:45:00 IST",
      },
      step3TrafficSanction: {
        completed: true,
        by: "Rajesh Verma (Executive Director - Railway Board)",
        timestamp: "2026-09-23 08:50:00 IST",
      },
      step4T806Issued: {
        completed: false,
      }
    },
    currentStep: 3,
    status: "SANCTIONED",
    issuingOfficer: "Rajesh Verma",
    issuingDesignation: "Executive Director (Railway Board - Central Authority)",
    participatingDepartments: ["Electrical (OHE)", "Operations (OCC)"],
    digitalSignatureHash: "4b227777d4dd1fc61c6f884f48641d02b4d121d3fd328cb08b5531fcacdabf8a",
    previousHash: "e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855",
    issuedAt: "23 Sep 2026, 08:50:00 IST",
    cautionOrderSummary: "TSR 30 km/h on Down Line KM 110-115; OHE Ladder Trolley on track."
  }
];

// ==========================================
// 6. 6 DESIGNATED RBAC PERSONAS
// ==========================================
export const MOCK_RBAC_PERSONAS: (UserProfile & { standardRole: string; permissions: string[] })[] = [
  {
    id: "USR-CIV-01",
    name: "Sunil Deshmukh",
    email: "civil@railplan.ai",
    role: "DEPT_USER",
    standardRole: "SECTION_ENGINEER_CIVIL",
    departmentId: "ENG",
    departmentName: "Civil Engineering (P-Way)",
    designation: "Senior Section Engineer (Permanent Way)",
    zone: "West Central Railway (WCR)",
    division: "Bhopal Division",
    permissions: [
      "CREATE_BLOCK_REQUEST",
      "VIEW_DIGITAL_TWIN",
      "RUN_AI_BUNDLER",
      "SUBMIT_T806_PROPOSAL",
      "UPDATE_WORK_PROGRESS"
    ]
  },
  {
    id: "USR-OHE-01",
    name: "K. Ramanathan",
    email: "ohe@railplan.ai",
    role: "DEPT_USER",
    standardRole: "OHE_ENGINEER",
    departmentId: "ELEC",
    departmentName: "Electrical Traction & OHE",
    designation: "Senior Divisional Electrical Engineer (Traction)",
    zone: "West Central Railway (WCR)",
    division: "Bhopal Division",
    permissions: [
      "CREATE_BLOCK_REQUEST",
      "VIEW_DIGITAL_TWIN",
      "RUN_AI_BUNDLER",
      "CONFIRM_OHE_ISOLATION",
      "SUBMIT_T806_PROPOSAL",
      "UPDATE_WORK_PROGRESS"
    ]
  },
  {
    id: "USR-SNT-01",
    name: "Ananya Sharma",
    email: "signal@railplan.ai",
    role: "DEPT_USER",
    standardRole: "SNT_ENGINEER",
    departmentId: "SNT",
    departmentName: "Signal & Telecom (Kavach TCAS)",
    designation: "Senior Section Engineer (Signal & Kavach)",
    zone: "West Central Railway (WCR)",
    division: "Bhopal Division",
    permissions: [
      "CREATE_BLOCK_REQUEST",
      "VIEW_DIGITAL_TWIN",
      "RUN_AI_BUNDLER",
      "SUBMIT_T806_PROPOSAL",
      "UPDATE_WORK_PROGRESS"
    ]
  },
  {
    id: "USR-OCC-01",
    name: "Rajesh Verma",
    email: "admin@railplan.ai",
    role: "CENTRAL_ADMIN",
    standardRole: "OCC_CHIEF_CONTROLLER",
    departmentId: "SFTY",
    departmentName: "Central Control Authority (Railway Board)",
    designation: "Executive Director (Railway Board)",
    zone: "Railway Board (Central Authority)",
    division: "Central Authority (Railway Board)",
    permissions: [
      "CREATE_BLOCK_REQUEST",
      "VIEW_DIGITAL_TWIN",
      "RUN_AI_BUNDLER",
      "APPROVE_AI_BUNDLE",
      "APPROVE_T806_SANCTION",
      "CONFIRM_EMERGENCY_REROUTING",
      "DISPATCH_OCC_ORDER",
      "MODIFY_SPEED_RESTRICTIONS",
      "VIEW_AUDIT_LOGS"
    ]
  },
  {
    id: "USR-SFTY-01",
    name: "Devendra Yadav",
    email: "safety@railplan.ai",
    role: "CENTRAL_ADMIN",
    standardRole: "SAFETY_OFFICER",
    departmentId: "SFTY",
    departmentName: "Safety Directorate & CRS Compliance",
    designation: "Divisional Safety Officer & CRS Inspector",
    zone: "West Central Railway (WCR)",
    division: "Safety Directorate",
    permissions: [
      "VIEW_DIGITAL_TWIN",
      "RUN_AI_BUNDLER",
      "APPROVE_T806_SANCTION",
      "CONFIRM_EMERGENCY_REROUTING",
      "OVERRIDE_SAFETY_INDEX",
      "VIEW_AUDIT_LOGS",
      "AUDIT_HASH_CHAIN"
    ]
  },
  {
    id: "USR-ADM-01",
    name: "Rajesh Verma",
    email: "admin@railplan.ai",
    role: "CENTRAL_ADMIN",
    standardRole: "ADMIN",
    departmentId: "OPS",
    departmentName: "Railway Board / Central Authority",
    designation: "Executive Director (Operations & Maintenance)",
    zone: "Railway Board (Central Authority)",
    division: "National Control Command, New Delhi",
    permissions: [
      "ALL_PERMISSIONS",
      "CREATE_BLOCK_REQUEST",
      "VIEW_DIGITAL_TWIN",
      "RUN_AI_BUNDLER",
      "APPROVE_AI_BUNDLE",
      "APPROVE_T806_SANCTION",
      "CONFIRM_EMERGENCY_REROUTING",
      "DISPATCH_OCC_ORDER",
      "RESET_SYSTEM_STATE",
      "VIEW_AUDIT_LOGS"
    ]
  }
];
