import { HorizonBlockPlan, HorizonScheduleSlot, PlanningHorizon } from "./types";

// =========================================================================
// SHORT-TERM WEEKLY BLOCK PLANS (Tactical 7-Day Rolling Horizon)
// Supports immediate tactical maintenance, night mega-blocks, and train regulation
// =========================================================================

export const WEEKLY_BLOCK_PLANS: HorizonBlockPlan[] = [
  {
    id: "HBP-WK-NDLS-MMCT-39",
    horizon: "WEEKLY",
    scope: "SHORT_TERM_MAINTENANCE",
    title: "Week 39 Rolling Short-Term Block Program (28 Sep - 04 Oct 2026)",
    periodLabel: "Week 39 • 28 Sep - 04 Oct 2026",
    corridorId: "NDLS-MMCT",
    totalBlockHours: 54.5,
    totalSlots: 14,
    departmentsInvolved: ["ENG", "ELEC", "SNT", "SFTY"],
    passengerTrainsRegulated: 6,
    averageDelayMinutesPerTrain: 11.5,
    freightCapacityImpactPct: 7.2,
    trackKmTargeted: 32.8,
    trackKmCompleted: 18.2,
    totalBudgetEstimated: 4250000,
    status: "IN_EXECUTION",
    conflictCheckPassed: true,
    aiOptimizationScore: 96,
    keyObjectives: [
      "Joint night mega-blocks between Mathura and Kota for ballast tamping and OHE contact wire dressing",
      "Ultrasonic Flaw Detection (USFD) scanning on high-stress 60kg 90UTS rail segments (KM 148-165)",
      "Zero disruption to 12952 Mumbai Rajdhani & 12010 Vande Bharat through dynamic shadow-pathing",
    ],
    criticalRisksMitigated: [
      "Elimination of rail fracture vulnerability before winter temperature variations",
      "Correction of 18mm catenary droop to prevent high-speed pantograph entanglements",
    ],
    slots: [
      {
        id: "SLOT-WK-01",
        horizon: "WEEKLY",
        dayOrPeriod: "Monday (28 Sep)",
        date: "2026-09-28",
        timeWindow: "01:30 - 05:30",
        durationHours: 4.0,
        trackLine: "UP_MAIN",
        corridorId: "NDLS-MMCT",
        fromKm: 148.0,
        toKm: 154.5,
        locationSection: "Mathura Jn - Bharatpur Jn (UP Line)",
        departmentId: "ENG",
        departmentName: "Civil Engineering (P-Way)",
        workType: "Continuous Welded Rail (CWR) De-stressing & CSM Tamping",
        machinery: ["CSM 09-3X Tamping Machine", "Ballast Regulating Machine BRM-112"],
        speedRestriction: "Track Closed • Post-work 45 km/h TSR for 12 hrs",
        passengerTrainsRegulated: ["12951 Mumbai Tejas Rajdhani (regulated 8 mins)"],
        freightImpact: "2 DFC container rakes stabled at Mathura yard loop",
        status: "COMPLETED",
        t806Id: "WCR/BPL-ET/T806/2026/044",
        riskScore: 28,
      },
      {
        id: "SLOT-WK-02",
        horizon: "WEEKLY",
        dayOrPeriod: "Monday (28 Sep)",
        date: "2026-09-28",
        timeWindow: "01:30 - 05:30",
        durationHours: 4.0,
        trackLine: "UP_MAIN",
        corridorId: "NDLS-MMCT",
        fromKm: 148.0,
        toKm: 154.5,
        locationSection: "Mathura Jn - Bharatpur Jn (Co-located OHE)",
        departmentId: "ELEC",
        departmentName: "Electrical / OHE Traction",
        workType: "25kV OHE Catenary Wire Re-tensioning & Insulator Wash",
        machinery: ["OHE Tower Wagon RU-82", "Hydro-wash Crane Rig"],
        speedRestriction: "25kV Traction Power Isolated (Permit to Work #718)",
        passengerTrainsRegulated: [],
        freightImpact: "Diesel hauling assist standby",
        status: "COMPLETED",
        riskScore: 24,
      },
      {
        id: "SLOT-WK-03",
        horizon: "WEEKLY",
        dayOrPeriod: "Tuesday (29 Sep)",
        date: "2026-09-29",
        timeWindow: "11:00 - 13:30",
        durationHours: 2.5,
        trackLine: "DOWN_MAIN",
        corridorId: "NDLS-MMCT",
        fromKm: 182.0,
        toKm: 186.2,
        locationSection: "Bayana - Gangapur City",
        departmentId: "SNT",
        departmentName: "Signal & Telecommunications",
        workType: "Kavach RFID Balise Recalibration & Dual Axle Counter Reset",
        machinery: ["Kavach Test Van-04", "Digital High-Frequency Scope"],
        speedRestriction: "Normal line speed • Caution board deployed",
        passengerTrainsRegulated: [],
        freightImpact: "Nil",
        status: "T806_SANCTIONED",
        riskScore: 16,
      },
      {
        id: "SLOT-WK-04",
        horizon: "WEEKLY",
        dayOrPeriod: "Wednesday (30 Sep)",
        date: "2026-09-30",
        timeWindow: "02:00 - 05:30",
        durationHours: 3.5,
        trackLine: "UP_MAIN",
        corridorId: "NDLS-MMCT",
        fromKm: 215.0,
        toKm: 221.0,
        locationSection: "Sawai Madhopur Jn - Kota Jn",
        departmentId: "ENG",
        departmentName: "Civil Engineering (P-Way)",
        workType: "Ballast Cleaning Machine (BCM) Deep Screening",
        machinery: ["BCM-341", "Muck Disposal Rake", "DGS Dynamic Track Stabilizer"],
        speedRestriction: "Track Closed • 30 km/h Caution Order for 48 hrs",
        passengerTrainsRegulated: ["12953 August Kranti Rajdhani (delayed 12 mins)"],
        freightImpact: "Freight diverted to chord line",
        status: "IN_PROGRESS",
        riskScore: 42,
      },
      {
        id: "SLOT-WK-05",
        horizon: "WEEKLY",
        dayOrPeriod: "Thursday (01 Oct)",
        date: "2026-10-01",
        timeWindow: "01:00 - 05:00",
        durationHours: 4.0,
        trackLine: "BOTH_MAIN",
        corridorId: "NDLS-MMCT",
        fromKm: 278.4,
        toKm: 284.0,
        locationSection: "Kota Yard Approaches",
        departmentId: "SNT",
        departmentName: "Signal & Traffic",
        workType: "Electronic Interlocking Route Verification & Point Motor Lubrication",
        machinery: ["Point Testing Rig PT-09"],
        speedRestriction: "Manual Hand-Signaling Protocol Active",
        passengerTrainsRegulated: ["12431 Trivandrum Rajdhani (regulated 10 mins)"],
        freightImpact: "Yard sorting operations suspended during window",
        status: "CONFIRMED",
        riskScore: 35,
      },
      {
        id: "SLOT-WK-06",
        horizon: "WEEKLY",
        dayOrPeriod: "Friday (02 Oct)",
        date: "2026-10-02",
        timeWindow: "02:00 - 05:30",
        durationHours: 3.5,
        trackLine: "DOWN_MAIN",
        corridorId: "NDLS-MMCT",
        fromKm: 340.0,
        toKm: 345.5,
        locationSection: "Shamgarh - Nagda Junction",
        departmentId: "ELEC",
        departmentName: "Electrical / OHE Traction",
        workType: "Catenary Auto-Tensioning Device (ATD) Pulley Replacement",
        machinery: ["OHE Tower Car RU-99"],
        speedRestriction: "OHE De-energized",
        passengerTrainsRegulated: [],
        freightImpact: "Nil",
        status: "SCHEDULED",
        riskScore: 22,
      },
      {
        id: "SLOT-WK-07",
        horizon: "WEEKLY",
        dayOrPeriod: "Saturday (03 Oct)",
        date: "2026-10-03",
        timeWindow: "00:30 - 05:30",
        durationHours: 5.0,
        trackLine: "UP_MAIN",
        corridorId: "NDLS-MMCT",
        fromKm: 388.0,
        toKm: 394.0,
        locationSection: "Ratlam Division High-Speed Curve",
        departmentId: "ENG",
        departmentName: "Civil Engineering (P-Way)",
        workType: "Track Relay Train (TRT) Sleeper & Rail Exchange",
        machinery: ["TRT-07 System", "CSM 09-3X Tamping Machine", "BRM-115"],
        speedRestriction: "Track Closed • 20 km/h Caution Order for 24 hrs",
        passengerTrainsRegulated: [
          "12009 Mumbai-Ahmedabad Shatabdi",
          "12908 Maharashtra Sampark Kranti (rescheduled +15m)"
        ],
        freightImpact: "3 container rakes regulated at Ratlam outer",
        status: "SCHEDULED",
        riskScore: 55,
      },
      {
        id: "SLOT-WK-08",
        horizon: "WEEKLY",
        dayOrPeriod: "Sunday (04 Oct)",
        date: "2026-10-04",
        timeWindow: "06:00 - 09:00",
        durationHours: 3.0,
        trackLine: "UP_MAIN",
        corridorId: "NDLS-MMCT",
        fromKm: 388.0,
        toKm: 394.0,
        locationSection: "Ratlam Division Curve (Daylight Inspection)",
        departmentId: "SFTY",
        departmentName: "Safety Directorate",
        workType: "Post-Work Track Recording Car (TRC) Speed Trial & CRS Compliance",
        machinery: ["TRC High-Speed Inspection Coach"],
        speedRestriction: "Speed Trial Run (Up to 110 km/h progressive)",
        passengerTrainsRegulated: [],
        freightImpact: "Nil",
        status: "SCHEDULED",
        riskScore: 18,
      },
    ],
  },
  {
    id: "HBP-WK-BPL-ET-39",
    horizon: "WEEKLY",
    scope: "SHORT_TERM_MAINTENANCE",
    title: "Week 39 Bhopal-Itarsi High-Density Short-Term Plan",
    periodLabel: "Week 39 • 28 Sep - 04 Oct 2026",
    corridorId: "BPL-ET",
    totalBlockHours: 36.0,
    totalSlots: 10,
    departmentsInvolved: ["ENG", "ELEC", "SNT"],
    passengerTrainsRegulated: 4,
    averageDelayMinutesPerTrain: 9.0,
    freightCapacityImpactPct: 5.8,
    trackKmTargeted: 22.4,
    trackKmCompleted: 14.0,
    totalBudgetEstimated: 2850000,
    status: "IN_EXECUTION",
    conflictCheckPassed: true,
    aiOptimizationScore: 98,
    keyObjectives: [
      "Mid-ghat section turnout replacement at Budni and Barkhera",
      "Joint mega-block (Civil + Electrical) for 25kV power cutoff during 02:00-06:00 low traffic slot",
      "Kavach safety integrity testing on steep gradient loops",
    ],
    criticalRisksMitigated: [
      "Prevent turnout tongue rail wear on heavy descending coal freight trains",
      "Neutral section flashover risk mitigation at KM 818",
    ],
    slots: [
      {
        id: "SLOT-BPL-01",
        horizon: "WEEKLY",
        dayOrPeriod: "Monday (28 Sep)",
        date: "2026-09-28",
        timeWindow: "02:00 - 05:30",
        durationHours: 3.5,
        trackLine: "UP_MAIN",
        corridorId: "BPL-ET",
        fromKm: 812.0,
        toKm: 816.5,
        locationSection: "Habibganj (Rani Kamlapati) - Mandideep",
        departmentId: "ENG",
        departmentName: "Civil Engineering",
        workType: "Track Tamping and Ballast Profiling",
        machinery: ["CSM-08", "BRM-90"],
        speedRestriction: "50 km/h Caution Order",
        passengerTrainsRegulated: ["20171 Vande Bharat Express (regulated 5 mins)"],
        freightImpact: "Coal rake held at Misrod loop",
        status: "COMPLETED",
        t806Id: "WCR/BPL-ET/T806/2026/044",
        riskScore: 22,
      },
      {
        id: "SLOT-BPL-02",
        horizon: "WEEKLY",
        dayOrPeriod: "Wednesday (30 Sep)",
        date: "2026-09-30",
        timeWindow: "01:30 - 05:30",
        durationHours: 4.0,
        trackLine: "BOTH_MAIN",
        corridorId: "BPL-ET",
        fromKm: 835.0,
        toKm: 842.0,
        locationSection: "Barkhera - Midghat Ghat Incline",
        departmentId: "ELEC",
        departmentName: "Electrical / OHE",
        workType: "OHE Catenary Wire Dropper Replacement & Mast Grounding Check",
        machinery: ["OHE Tower Wagon WCR-14"],
        speedRestriction: "25kV Power Block Required",
        passengerTrainsRegulated: ["12156 Bhopal Express (regulated 10 mins)"],
        freightImpact: "Ghat banking engine repositioned",
        status: "IN_PROGRESS",
        riskScore: 36,
      },
      {
        id: "SLOT-BPL-03",
        horizon: "WEEKLY",
        dayOrPeriod: "Saturday (03 Oct)",
        date: "2026-10-03",
        timeWindow: "02:00 - 06:00",
        durationHours: 4.0,
        trackLine: "DOWN_MAIN",
        corridorId: "BPL-ET",
        fromKm: 875.0,
        toKm: 880.0,
        locationSection: "Hoshangabad Narmada Bridge Approaches",
        departmentId: "ENG",
        departmentName: "Civil Engineering",
        workType: "Bridge Expansion Joint Rubber Sealing & Rail Lubrication",
        machinery: ["Portable Tamping Tools", "Hydraulic Jack Sets"],
        speedRestriction: "30 km/h TSR on Bridge Piers",
        passengerTrainsRegulated: ["12808 Samta Express (regulated 7 mins)"],
        freightImpact: "Nil",
        status: "CONFIRMED",
        riskScore: 30,
      },
    ],
  },
  {
    id: "HBP-WK-NDLS-HWH-39",
    horizon: "WEEKLY",
    scope: "SHORT_TERM_MAINTENANCE",
    title: "Week 39 Grand Chord Eastern Trunk Short-Term Block Program",
    periodLabel: "Week 39 • 28 Sep - 04 Oct 2026",
    corridorId: "NDLS-HWH",
    totalBlockHours: 48.0,
    totalSlots: 12,
    departmentsInvolved: ["ENG", "ELEC", "SNT"],
    passengerTrainsRegulated: 7,
    averageDelayMinutesPerTrain: 14.0,
    freightCapacityImpactPct: 8.5,
    trackKmTargeted: 35.0,
    trackKmCompleted: 21.0,
    totalBudgetEstimated: 4900000,
    status: "IN_EXECUTION",
    conflictCheckPassed: true,
    aiOptimizationScore: 94,
    keyObjectives: [
      "Kanpur Central Yard throat points tamping & electronic interlocking servicing",
      "Overhead feeder cable renewal at Mughalsarai / Pt. Deen Dayal Upadhyaya bypass",
      "Protection of Howrah Rajdhani and Poorva Express timetables",
    ],
    criticalRisksMitigated: [
      "Point failure mitigation at major Diamond Crossing",
      "Traction substation surge arrester replacement",
    ],
    slots: [
      {
        id: "SLOT-HWH-01",
        horizon: "WEEKLY",
        dayOrPeriod: "Tuesday (29 Sep)",
        date: "2026-09-29",
        timeWindow: "01:00 - 05:00",
        durationHours: 4.0,
        trackLine: "UP_MAIN",
        corridorId: "NDLS-HWH",
        fromKm: 435.0,
        toKm: 441.0,
        locationSection: "Kanpur Central Approach",
        departmentId: "ENG",
        departmentName: "Civil Engineering",
        workType: "Thick Web Switch (TWS) 1:12 Turnout Overhaul",
        machinery: ["Unimat 08-4S Turnout Tamper"],
        speedRestriction: "Track Block • 30 km/h Caution Order",
        passengerTrainsRegulated: ["12302 Howrah Rajdhani (held 14 mins at Rura)"],
        freightImpact: "4 freight rakes held on DFC interchange line",
        status: "COMPLETED",
        riskScore: 38,
      },
      {
        id: "SLOT-HWH-02",
        horizon: "WEEKLY",
        dayOrPeriod: "Thursday (01 Oct)",
        date: "2026-10-01",
        timeWindow: "02:00 - 05:30",
        durationHours: 3.5,
        trackLine: "DOWN_MAIN",
        corridorId: "NDLS-HWH",
        fromKm: 580.0,
        toKm: 586.5,
        locationSection: "Prayagraj Chheoki - Mirzapur",
        departmentId: "ELEC",
        departmentName: "Electrical / OHE",
        workType: "Traction Substation (TSS) Capacitor Bank Testing & Isolator Overhaul",
        machinery: ["OHE Inspection Car RU-61"],
        speedRestriction: "Single Phase Power Feed Redistribution",
        passengerTrainsRegulated: ["12382 Poorva Express (regulated 10 mins)"],
        freightImpact: "Nil",
        status: "CONFIRMED",
        riskScore: 25,
      },
    ],
  },
];

// =========================================================================
// LONG-TERM MONTHLY BLOCK PLANS (Strategic 30-Day / 4-Week Master Horizon)
// Supports major track renewals, capital overhaul, BCM deep screening, and seasonal planning
// =========================================================================

export const MONTHLY_BLOCK_PLANS: HorizonBlockPlan[] = [
  {
    id: "HBP-MO-NDLS-MMCT-2026-10",
    horizon: "MONTHLY",
    scope: "LONG_TERM_MAINTENANCE",
    title: "October 2026 Master Corridor Overhaul & Capital Renewal Program",
    periodLabel: "October 2026 • 30-Day Master",
    corridorId: "NDLS-MMCT",
    totalBlockHours: 236.0,
    totalSlots: 28,
    departmentsInvolved: ["ENG", "ELEC", "SNT", "SFTY"],
    passengerTrainsRegulated: 18,
    averageDelayMinutesPerTrain: 8.5,
    freightCapacityImpactPct: 6.4,
    trackKmTargeted: 148.5,
    trackKmCompleted: 42.0,
    totalBudgetEstimated: 18500000,
    status: "BOARD_APPROVED",
    conflictCheckPassed: true,
    aiOptimizationScore: 97,
    keyObjectives: [
      "Execute complete Track Renewal Program (TRR/TSR) across 65 km of high-density trunk track",
      "Deploy Ballast Cleaning Machine (BCM-341) deep screening to restore drainage cushion before winter",
      "Modernize 28 route-km of 25kV OHE catenary to support 160 km/h Mission Raftaar operations",
      "CRS Certification of 4 rebuilt major steel girder bridges between Mathura and Vadodara",
    ],
    criticalRisksMitigated: [
      "Complete elimination of recurring speed restrictions (TSRs) across Ratlam and Kota divisions",
      "Pre-fog Kavach Level 2 electronic safety interlock calibration across all interlockings",
      "Bridge pier scour and expansion bearing restoration safeguarding passenger express rakes",
    ],
    slots: [
      {
        id: "SLOT-MO-01",
        horizon: "MONTHLY",
        dayOrPeriod: "Week 1 (01 - 07 Oct)",
        date: "2026-10-01",
        timeWindow: "Nightly 01:00 - 05:30 (4-Day Window)",
        durationHours: 18.0,
        trackLine: "UP_MAIN",
        corridorId: "NDLS-MMCT",
        fromKm: 138.0,
        toKm: 165.0,
        locationSection: "Mathura - Bharatpur Sector (Track Renewal 01)",
        departmentId: "ENG",
        departmentName: "Civil Engineering (P-Way)",
        workType: "Heavy 60kg 90UTS Continuous Rail Replacement & PSC Sleeper Relay",
        machinery: ["Track Relay Train TRT-07", "DGS Dynamic Track Stabilizer", "CSM 09-3X"],
        speedRestriction: "Progressive TSR relaxing from 30 km/h to 130 km/h over 7 days",
        passengerTrainsRegulated: ["12952 Mumbai Rajdhani", "12954 August Kranti"],
        freightImpact: "Regulated stabling during midnight window; routed via chord line",
        status: "CONFIRMED",
        riskScore: 48,
      },
      {
        id: "SLOT-MO-02",
        horizon: "MONTHLY",
        dayOrPeriod: "Week 1 (01 - 07 Oct)",
        date: "2026-10-04",
        timeWindow: "Sunday 06:00 - 14:00 (Daylight Possession)",
        durationHours: 8.0,
        trackLine: "BOTH_MAIN",
        corridorId: "NDLS-MMCT",
        fromKm: 210.0,
        toKm: 215.0,
        locationSection: "Chambal Major River Viaduct (Bridge #142)",
        departmentId: "ENG",
        departmentName: "Civil Engineering (Bridges)",
        workType: "Steel Girder Ultrasonic Inspection, Bearing Replacement & Anti-Corrosion Epoxy Coating",
        machinery: ["Hydraulic Synchronized Jack Rig", "Inspection Cherry Picker Rail-Mount"],
        speedRestriction: "Line Closed for 8H • 20 km/h Caution Order for 72 hrs",
        passengerTrainsRegulated: [
          "12009 Shatabdi Express (diverted via Agra-Gwalior)",
          "12908 Sampark Kranti (rescheduled +45m)"
        ],
        freightImpact: "Heavy coal rakes held at Bayana and Gangapur City",
        status: "BOARD_APPROVED",
        riskScore: 65,
      },
      {
        id: "SLOT-MO-03",
        horizon: "MONTHLY",
        dayOrPeriod: "Week 2 (08 - 14 Oct)",
        date: "2026-10-09",
        timeWindow: "Nightly 01:30 - 05:30 (5-Day Rolling)",
        durationHours: 20.0,
        trackLine: "DOWN_MAIN",
        corridorId: "NDLS-MMCT",
        fromKm: 285.0,
        toKm: 315.0,
        locationSection: "Kota Division South Sector",
        departmentId: "ELEC",
        departmentName: "Electrical / OHE Traction",
        workType: "Complete 25kV OHE Catenary Wire & Contact Wire Overhaul (107 sq mm Cadmium-Copper)",
        machinery: ["3x OHE Wiring Trains", "Tower Cars RU-82 & RU-99"],
        speedRestriction: "Traction Power Shut • Diesel Pilot Escorts Deployed",
        passengerTrainsRegulated: ["12431 Trivandrum Rajdhani (regulated 12 mins)"],
        freightImpact: "Electric freight staged; diesel rakes permitted on adjoining DFC",
        status: "SCHEDULED",
        riskScore: 35,
      },
      {
        id: "SLOT-MO-04",
        horizon: "MONTHLY",
        dayOrPeriod: "Week 3 (15 - 21 Oct)",
        date: "2026-10-16",
        timeWindow: "Weekend 00:00 - 08:00 (Major Mega Possession)",
        durationHours: 8.0,
        trackLine: "BOTH_MAIN",
        corridorId: "NDLS-MMCT",
        fromKm: 410.0,
        toKm: 418.0,
        locationSection: "Nagda Junction Complex (Major Interlocking)",
        departmentId: "SNT",
        departmentName: "Signal & Telecommunications",
        workType: "Commissioning of Electronic Interlocking (EI) Mk-IV with Centralized Traffic Control (CTC)",
        machinery: ["EI Cutover Testing Vans", "Digital Signal Analyzer Rig"],
        speedRestriction: "Emergency G&SR Section 15.06 Hand-Signaling Pilots Active",
        passengerTrainsRegulated: [
          "12951 Mumbai Tejas Rajdhani (rescheduled 20 mins)",
          "12953 August Kranti (regulated 25 mins)",
          "12010 Vande Bharat Express (regulated 15 mins)"
        ],
        freightImpact: "Yard sorting shut for 8 hours; freight pre-cleared via loops",
        status: "BOARD_APPROVED",
        riskScore: 72,
      },
      {
        id: "SLOT-MO-05",
        horizon: "MONTHLY",
        dayOrPeriod: "Week 4 (22 - 28 Oct)",
        date: "2026-10-24",
        timeWindow: "Nightly 01:30 - 05:00 (4-Day Window)",
        durationHours: 14.0,
        trackLine: "UP_MAIN",
        corridorId: "NDLS-MMCT",
        fromKm: 480.0,
        toKm: 512.0,
        locationSection: "Ratlam - Godhra Section",
        departmentId: "ENG",
        departmentName: "Civil Engineering",
        workType: "Rail Grinding Machine (RGM) Treatment for RCF (Rolling Contact Fatigue) Prevention",
        machinery: ["72-Stone Rail Grinder RGM-04", "Fire-Fighting Tender Unit"],
        speedRestriction: "Track Closed during grinding • Restored to 130 km/h immediately",
        passengerTrainsRegulated: ["12952 Mumbai Rajdhani (shadowed behind RGM safely)"],
        freightImpact: "Nil",
        status: "SCHEDULED",
        riskScore: 32,
      },
      {
        id: "SLOT-MO-06",
        horizon: "MONTHLY",
        dayOrPeriod: "Week 4 (29 - 31 Oct)",
        date: "2026-10-30",
        timeWindow: "Daylight 08:00 - 16:00",
        durationHours: 8.0,
        trackLine: "BOTH_MAIN",
        corridorId: "NDLS-MMCT",
        fromKm: 138.0,
        toKm: 512.0,
        locationSection: "Corridor-Wide Speed Certification",
        departmentId: "SFTY",
        departmentName: "Safety Directorate & CRS Inspection",
        workType: "Monthly Comprehensive Oscillation Trial & CRS 160 km/h Corridor Sanction Audit",
        machinery: ["Oscillograph Car", "Laser Track Geometry Car OMS-2000"],
        speedRestriction: "Special High-Speed Trial Windows (160 km/h)",
        passengerTrainsRegulated: [],
        freightImpact: "Freight cleared to side loops",
        status: "SCHEDULED",
        riskScore: 20,
      },
    ],
  },
  {
    id: "HBP-MO-BPL-ET-2026-10",
    horizon: "MONTHLY",
    scope: "LONG_TERM_MAINTENANCE",
    title: "October 2026 Bhopal-Itarsi Strategic Ghat & Bridge Overhaul Plan",
    periodLabel: "October 2026 • 30-Day Master",
    corridorId: "BPL-ET",
    totalBlockHours: 154.0,
    totalSlots: 20,
    departmentsInvolved: ["ENG", "ELEC", "SNT", "SFTY"],
    passengerTrainsRegulated: 12,
    averageDelayMinutesPerTrain: 9.5,
    freightCapacityImpactPct: 5.2,
    trackKmTargeted: 92.0,
    trackKmCompleted: 34.0,
    totalBudgetEstimated: 12200000,
    status: "BOARD_APPROVED",
    conflictCheckPassed: true,
    aiOptimizationScore: 99,
    keyObjectives: [
      "Mid-ghat section slope stabilization, rock-bolting, and catch-water drain renovation before winter rains",
      "Full renewal of 8 diamond turnouts across Bhopal and Itarsi junction yards",
      "Substation feeder transformer overhaul at Budni TSS",
    ],
    criticalRisksMitigated: [
      "Elimination of boulder fall hazard along steep 1:80 ghat incline at KM 838",
      "Track buckling prevention through systematic destressing at 48°C rail neutral temperature",
    ],
    slots: [
      {
        id: "SLOT-BPL-MO-01",
        horizon: "MONTHLY",
        dayOrPeriod: "Week 1 (01 - 07 Oct)",
        date: "2026-10-02",
        timeWindow: "01:30 - 05:30 (Night Possession)",
        durationHours: 4.0,
        trackLine: "UP_MAIN",
        corridorId: "BPL-ET",
        fromKm: 810.0,
        toKm: 825.0,
        locationSection: "Bhopal - Rani Kamlapati (Habibganj)",
        departmentId: "ENG",
        departmentName: "Civil Engineering",
        workType: "Turnout 1:12 Thick Web Switch Replacement and Flash-Butt Welding",
        machinery: ["Unimat 08-4S", "Mobile Flash Butt Welder FBW-12"],
        speedRestriction: "30 km/h TSR for 48 hrs",
        passengerTrainsRegulated: ["20171 Vande Bharat (regulated 8 mins)"],
        freightImpact: "Held at Nishatpura yard",
        status: "CONFIRMED",
        riskScore: 34,
      },
      {
        id: "SLOT-BPL-MO-02",
        horizon: "MONTHLY",
        dayOrPeriod: "Week 2 (08 - 14 Oct)",
        date: "2026-10-10",
        timeWindow: "01:00 - 06:00 (5-Hour Joint Possession)",
        durationHours: 5.0,
        trackLine: "BOTH_MAIN",
        corridorId: "BPL-ET",
        fromKm: 835.0,
        toKm: 846.0,
        locationSection: "Barkhera - Midghat Ghat Tunnel #2 & Cutting",
        departmentId: "ELEC",
        departmentName: "Electrical / OHE",
        workType: "Tunnel Rigid Catenary System (ROCS) Clearance Adjustment & Insulator Replacement",
        machinery: ["Tunnel Inspection Rail Car", "OHE Tower Car"],
        speedRestriction: "Power Cut • Pilot Escorts Active",
        passengerTrainsRegulated: ["12156 Bhopal Express", "12808 Samta Express"],
        freightImpact: "Ghat banking trains regulated",
        status: "BOARD_APPROVED",
        riskScore: 58,
      },
      {
        id: "SLOT-BPL-MO-03",
        horizon: "MONTHLY",
        dayOrPeriod: "Week 3 (15 - 21 Oct)",
        date: "2026-10-18",
        timeWindow: "02:00 - 06:00 (Ghat Bridge Section)",
        durationHours: 4.0,
        trackLine: "DOWN_MAIN",
        corridorId: "BPL-ET",
        fromKm: 868.0,
        toKm: 874.0,
        locationSection: "Narmada Bridge Hoshangabad",
        departmentId: "ENG",
        departmentName: "Civil Engineering",
        workType: "Substructure Pier Pier-Cap Grouting & Guard Rail Re-alignment",
        machinery: ["Pressure Grouting Equipment", "Tamping Unit"],
        speedRestriction: "40 km/h Caution Order",
        passengerTrainsRegulated: ["12616 Grand Trunk Express (regulated 11 mins)"],
        freightImpact: "Nil",
        status: "SCHEDULED",
        riskScore: 40,
      },
      {
        id: "SLOT-BPL-MO-04",
        horizon: "MONTHLY",
        dayOrPeriod: "Week 4 (22 - 28 Oct)",
        date: "2026-10-25",
        timeWindow: "01:00 - 05:00 (Itarsi Junction Approach)",
        durationHours: 4.0,
        trackLine: "BOTH_MAIN",
        corridorId: "BPL-ET",
        fromKm: 885.0,
        toKm: 892.0,
        locationSection: "Itarsi Junction North Yard (A-Cabin)",
        departmentId: "SNT",
        departmentName: "Signal & Traffic",
        workType: "Kavach 4.0 Collision Avoidance Track RFID Tag Upgrades & Automatic Block Signaling Audit",
        machinery: ["Kavach Engineering Van", "Optical Fiber Testing Kit"],
        speedRestriction: "Absolute Block Working Standby",
        passengerTrainsRegulated: ["12722 Dakshin Express (held 10 mins at Powarkheda)"],
        freightImpact: "Freight sorting regulated at Itarsi hump",
        status: "SCHEDULED",
        riskScore: 32,
      },
    ],
  },
  {
    id: "HBP-MO-NDLS-HWH-2026-10",
    horizon: "MONTHLY",
    scope: "LONG_TERM_MAINTENANCE",
    title: "October 2026 Eastern Trunk Grand Chord Long-Term Corridor Program",
    periodLabel: "October 2026 • 30-Day Master",
    corridorId: "NDLS-HWH",
    totalBlockHours: 248.0,
    totalSlots: 32,
    departmentsInvolved: ["ENG", "ELEC", "SNT", "SFTY"],
    passengerTrainsRegulated: 24,
    averageDelayMinutesPerTrain: 12.0,
    freightCapacityImpactPct: 9.0,
    trackKmTargeted: 165.0,
    trackKmCompleted: 58.0,
    totalBudgetEstimated: 21500000,
    status: "BOARD_APPROVED",
    conflictCheckPassed: true,
    aiOptimizationScore: 95,
    keyObjectives: [
      "Overhaul 75 km of heavy freight track between Pt. Deen Dayal Upadhyaya and Dhanbad (Grand Chord)",
      "Re-catenary 40 km of high-density 25kV OHE section in Prayagraj division",
      "Kavach Level 2 electronic interlocking cutover across 12 wayside stations",
    ],
    criticalRisksMitigated: [
      "Prevent turnout point failure at high-density Kanpur yard throat",
      "Bridge pier scour inspection on Yamuna and Ganga river crossings",
    ],
    slots: [
      {
        id: "SLOT-HWH-MO-01",
        horizon: "MONTHLY",
        dayOrPeriod: "Week 1 (01 - 07 Oct)",
        date: "2026-10-03",
        timeWindow: "Nightly 01:00 - 05:30",
        durationHours: 4.5,
        trackLine: "UP_MAIN",
        corridorId: "NDLS-HWH",
        fromKm: 420.0,
        toKm: 445.0,
        locationSection: "Kanpur Approach Sector",
        departmentId: "ENG",
        departmentName: "Civil Engineering",
        workType: "Track Relay Train Sleeper Replacement & BCM Ballast Cleaning",
        machinery: ["TRT-04", "BCM-312", "CSM-12"],
        speedRestriction: "Track Closed • 30 km/h Caution Order",
        passengerTrainsRegulated: ["12302 Howrah Rajdhani (delayed 15 mins)"],
        freightImpact: "Diverted to EDFC freight line",
        status: "CONFIRMED",
        riskScore: 50,
      },
      {
        id: "SLOT-HWH-MO-02",
        horizon: "MONTHLY",
        dayOrPeriod: "Week 3 (15 - 21 Oct)",
        date: "2026-10-17",
        timeWindow: "01:30 - 06:00 (Joint Window)",
        durationHours: 4.5,
        trackLine: "BOTH_MAIN",
        corridorId: "NDLS-HWH",
        fromKm: 650.0,
        toKm: 662.0,
        locationSection: "Pt. Deen Dayal Upadhyaya Junction Bypass",
        departmentId: "ELEC",
        departmentName: "Electrical / OHE",
        workType: "25kV Auto-Tensioning Device (ATD) Overhaul & Section Insulator Testing",
        machinery: ["OHE Tower Car ECR-08"],
        speedRestriction: "Power Isolated",
        passengerTrainsRegulated: ["12382 Poorva Express (regulated 12 mins)"],
        freightImpact: "EDFC heavy haul rakes given precedence",
        status: "BOARD_APPROVED",
        riskScore: 36,
      },
    ],
  },
  {
    id: "HBP-MO-WDFC-2026-10",
    horizon: "MONTHLY",
    scope: "LONG_TERM_MAINTENANCE",
    title: "October 2026 Western DFC Heavy Haul 32.5T Axle Load Corridor Master Plan",
    periodLabel: "October 2026 • 30-Day Master",
    corridorId: "WDFC-01",
    totalBlockHours: 180.0,
    totalSlots: 22,
    departmentsInvolved: ["ENG", "ELEC", "SNT", "SFTY"],
    passengerTrainsRegulated: 0, // Dedicated freight corridor! Zero passenger trains
    averageDelayMinutesPerTrain: 0,
    freightCapacityImpactPct: 12.5,
    trackKmTargeted: 120.0,
    trackKmCompleted: 45.0,
    totalBudgetEstimated: 14500000,
    status: "BOARD_APPROVED",
    conflictCheckPassed: true,
    aiOptimizationScore: 99,
    keyObjectives: [
      "Maintain heavy haul 32.5 Ton axle load track integrity for double-stack container rakes",
      "Dynamic track stabilization and ballast depth restoration across Rajasthan & Gujarat sections",
      "Zero passenger impact; all blocks coordinated around Mundra & Pipavav port train windows",
    ],
    criticalRisksMitigated: [
      "Prevent gauge spreading and fishplate shearing under double-stack container stress",
      "Maintain high-rise 25kV OHE catenary clearance (7.1m) for double stack trains",
    ],
    slots: [
      {
        id: "SLOT-WDFC-MO-01",
        horizon: "MONTHLY",
        dayOrPeriod: "Week 2 (08 - 14 Oct)",
        date: "2026-10-11",
        timeWindow: "10:00 - 16:00 (Daylight Freight Gap)",
        durationHours: 6.0,
        trackLine: "DFC_FREIGHT",
        corridorId: "WDFC-01",
        fromKm: 720.0,
        toKm: 745.0,
        locationSection: "Palanpur - Sanand Dedicated Sector",
        departmentId: "ENG",
        departmentName: "Civil Engineering",
        workType: "Heavy-Haul Continuous Tamping & Rail Ultrasonic Flaw Detection (USFD)",
        machinery: ["High-Speed Track Tamper 09-32", "USFD Rail Tester Unit"],
        speedRestriction: "Single Track Freight Working on double line section",
        passengerTrainsRegulated: [],
        freightImpact: "Double-stack containers staggered by 30 mins",
        status: "CONFIRMED",
        riskScore: 28,
      },
    ],
  },
];

// Combine all horizon plans
export const ALL_HORIZON_BLOCK_PLANS: HorizonBlockPlan[] = [
  ...WEEKLY_BLOCK_PLANS,
  ...MONTHLY_BLOCK_PLANS,
];

// Helper functions for Horizon Plans
export function getHorizonPlans(
  horizon: PlanningHorizon,
  corridorId: string = "ALL"
): HorizonBlockPlan[] {
  return ALL_HORIZON_BLOCK_PLANS.filter((plan) => {
    const matchesHorizon = plan.horizon === horizon;
    const matchesCorridor = corridorId === "ALL" || plan.corridorId === corridorId;
    return matchesHorizon && matchesCorridor;
  });
}

export function getHorizonPlanById(id: string): HorizonBlockPlan | undefined {
  return ALL_HORIZON_BLOCK_PLANS.find((p) => p.id === id);
}

export function getHorizonKpis(horizon: PlanningHorizon, corridorId: string = "ALL") {
  const plans = getHorizonPlans(horizon, corridorId);
  const totalHours = plans.reduce((acc, p) => acc + p.totalBlockHours, 0);
  const totalSlots = plans.reduce((acc, p) => acc + p.totalSlots, 0);
  const totalTrackKm = plans.reduce((acc, p) => acc + p.trackKmTargeted, 0);
  const completedKm = plans.reduce((acc, p) => acc + (p.trackKmCompleted || 0), 0);
  const totalBudget = plans.reduce((acc, p) => acc + p.totalBudgetEstimated, 0);
  const avgDelay = plans.length > 0 
    ? (plans.reduce((acc, p) => acc + p.averageDelayMinutesPerTrain, 0) / plans.length).toFixed(1) 
    : "0.0";
  const avgScore = plans.length > 0
    ? Math.round(plans.reduce((acc, p) => acc + p.aiOptimizationScore, 0) / plans.length)
    : 96;

  return {
    totalHours: Number(totalHours.toFixed(1)),
    totalSlots,
    totalTrackKm: Number(totalTrackKm.toFixed(1)),
    completedKm: Number(completedKm.toFixed(1)),
    completionPct: totalTrackKm > 0 ? Math.round((completedKm / totalTrackKm) * 100) : 0,
    totalBudget,
    avgDelay: Number(avgDelay),
    avgScore,
    plansCount: plans.length,
  };
}
